### PR TITLE
fix: Dislay an error when trying to transfer safe token

### LINKED ISSUE #1244: [Safe tokens] - Warning "no transfer possible" is not shown in send funds modal
## Bug description
Currently if you choose to send the Safe Tokens in the send funds a warning should display saying that these tokens are non-transferable and the submit button is disabled. This behaviour is missing in web-core

## Environment
 - Browser: Chrome
 - Wallet: Any
 - Chain: Ethereum mainnet
 - Env: https://app.safe.global/

## Steps to reproduce
 1. Need a safe with Safe tokens
 2. Go to the Send funds modal and pick the Safe token

## Expected result
A message saying "SAFE is currently non-transferable" shows

## Obtained result
No error is shown, you can keep going to the review step

## Screenshots
Safe react prod:
image

Web core prod:
image

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #1244 

## How this PR fixes it

- Checks the `unpaused` property of the safe token contract
- Displays an error message and disables the next button if the safe token is selected in the transfer modal

## How to test it

1. Open a Safe on Mainnet that has Safe Tokens
2. Try to transfer them
3. Observe an error message and the next button being disabled
4. Select a different token
5. Observe the Next button becoming enabled again

## Screenshots
Screenshot 2022-11-25 at 12 19 59

### CODE REVIEW

File: src/components/tx/modals/TokenTransferModal/useSafeTokenWarning.ts [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+  const provider = useWeb3ReadOnly()
+
+  const [isSafeTokenPaused] = useAsync<boolean>(async () => {
+    const safeTokenAddress = getSafeTokenAddress(chainId)
+
+    const safeTokenContract = new Contract(
+      safeTokenAddress,
+      new Interface(['function paused() public view virtual returns (bool)']),
+      provider,
+    )
```
Comment (usame-algan) [inline src/components/tx/modals/TokenTransferModal/useSafeTokenWarning.ts:20]: I opted for calling the contract as this will not require a precise redeployment if the token becomes unpaused

File: src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx [hunk 2]
```diff
@@ -149,11 +162,20 @@ const SendAssetsForm = ({ onSubmit, formData }: SendAssetsFormProps): ReactEleme
             </Select>
           </FormControl>
 
+          {isDisabled && (
+            <Box mt={1} display="flex" alignItems="center">
+              <SvgIcon component={InfoIcon} color="error" fontSize="small" />
+              <Typography variant="body2" color="error" ml={0.5}>
+                SAFE is currently non-transferable.
```
Comment (iamacook) [inline src/components/tx/modals/TokenTransferModal/SendAssetsForm.tsx:169]:
```suggestion
                $SAFE is currently non-transferable.
```

File: src/components/tx/modals/TokenTransferModal/useSafeTokenWarning.ts [hunk 3]
```diff
@@ -0,0 +1,30 @@
+import useChainId from '@/hooks/useChainId'
+import { getSafeTokenAddress } from '@/components/common/SafeTokenWidget'
+import { useWeb3ReadOnly } from '@/hooks/wallets/web3'
+import useAsync from '@/hooks/useAsync'
+import { Contract } from 'ethers'
+import { Interface } from '@ethersproject/abi'
+
+// TODO: Remove this hook after the safe token has been unpaused
+const useSafeTokenWarning = () => {
```
Comment (iamacook) [inline src/components/tx/modals/TokenTransferModal/useSafeTokenWarning.ts:9]: Nit: I'd rename this to `useIsSafeTokenPaused` and return a `boolean`. I was expecting this to return the string, which we could alternatively do of course.

File: src/components/tx/modals/TokenTransferModal/useSafeTokenWarning.ts [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+  const chainId = useChainId()
+  const provider = useWeb3ReadOnly()
+
+  const [isSafeTokenPaused] = useAsync<boolean>(async () => {
+    const safeTokenAddress = getSafeTokenAddress(chainId)
+
+    const safeTokenContract = new Contract(
+      safeTokenAddress,
+      new Interface(['function paused() public view virtual returns (bool)']),
```
Comment (iamacook) [inline src/components/tx/modals/TokenTransferModal/useSafeTokenWarning.ts:18]: Let's extract this to a constant.

File: src/components/tx/modals/TokenTransferModal/useSafeTokenWarning.ts [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+
+// TODO: Remove this hook after the safe token has been unpaused
+const useSafeTokenWarning = () => {
+  const chainId = useChainId()
+  const provider = useWeb3ReadOnly()
+
+  const [isSafeTokenPaused] = useAsync<boolean>(async () => {
+    const safeTokenAddress = getSafeTokenAddress(chainId)
+
+    const safeTokenContract = new Contract(
```
Comment (iamacook) [inline src/components/tx/modals/TokenTransferModal/useSafeTokenWarning.ts:16]: We should probably catch this and return `false` if it throws.

**Comment by francovenica** [comment]
LGTM

image
