### PR TITLE
fix: Anonymize safe address on gtm init

### LINKED ISSUE #1034: GA is tracking user_engamenet
## Bug description
We should somehow disable the tracking of the `user_engagement` metric because it captures the full non-anonymized page URL.
Or, alternatively, make it not track the full URL.

Screenshot 2022-11-02 at 13 22 04

According to @usame-algan, it should be possible by setting an anonymized URL in the initial data layer.

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #1034 

## How this PR fixes it

Sets anonymized path and location in dataLayer when initializing GTM

## How to test it

1. Open the Safe with DebugView
2. Reload the page
3. Scroll around
4. Observe a `user_engagement` event with anonymized path and location values

## Screenshots
Screenshot 2022-11-03 at 09 10 30
Screenshot 2022-11-03 at 09 10 33

### CODE REVIEW

File: src/services/analytics/gtm.ts [hunk 1]
```diff
@@ -56,10 +76,14 @@ export const gtmInit = (): void => {
     return
   }
 
+  const pagePath = getAnonymizedPathname()
+
   TagManager.initialize({
     gtmId: GOOGLE_TAG_MANAGER_ID,
     ...GTM_ENVIRONMENT,
     dataLayer: {
+      pageLocation: `${location.origin}${pagePath}`,
```
Comment (iamacook) [inline src/services/analytics/gtm.ts:85]: In my tests, `router.pathname` doesn't include our rewrites. We could pass it as an argument to `gtmInit` and then not need anonymise the `pathname`.

Comment (usame-algan) [reply src/services/analytics/gtm.ts:85]: Good idea! It works nicely although we have to exclude it from the dependency array but I think it should be fine since it is only needed on the initial load.

File: src/services/analytics/useGtm.ts [hunk 2]
```diff
@@ -19,7 +19,8 @@ const useGtm = () => {
 
   // Initialize GTM, or clear it if analytics is disabled
   useEffect(() => {
-    isAnalyticsEnabled ? gtmInit() : gtmClear()
+    isAnalyticsEnabled ? gtmInit(router.pathname) : gtmClear()
+    // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (iamacook) [inline src/services/analytics/useGtm.ts:23]: Can you add a comment why we need to do this please.

File: src/utils/url.ts [hunk 3]
```diff
@@ -5,7 +5,8 @@ const trimTrailingSlash = (url: string): string => {
 const isSameUrl = (url1: string, url2: string): boolean => {
   return trimTrailingSlash(url1) === trimTrailingSlash(url2)
 }
-
+export const prefixedAddressRe = /[a-z0-9-]+\:0x[a-f0-9]{40}/i
+export const addressRe = /0x[a-f0-9]{40}/i
```
Comment (iamacook) [inline src/utils/url.ts:9]: This is not being used anymore.

**Review by iamacook — APPROVED** [review]
