### PR TITLE
fix: add signing to pending tx states

### LINKED ISSUE #872: [Queued list] The loading state  during tx signing is not displayed after switching between the tabs
## Bug description
The loading state  during tx signing is not displayed after switching between the tabs
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: goerli

## Steps to reproduce
 1. Go to the queued list in the 2 of N safe
 2. creat tx
 3.  confirm tx as the second use and go to the history and back to queued before the "Need your confirmation" is changed to the " Need execution."
Current result: There is no "loading state, and the user is lost on what should be done next.
In some time "Need your confirmation" is updated to "Need execution" without any action from the user

## Expected result
Make sure that the loading state is displayed after the tab switch 

## Screenshots
https://drive.google.com/file/d/1sY0_hJa7k5nYw9DlRoxB-iGKDN5ndpfO/view?usp=sharing

### PR DESCRIPTION
**Pull request by schmanu**
## What it solves
There is a delay of a few seconds between signing a queued tx and receiving the new signature from the tx services. 
Currently the pending signature is only reflected by the signing button and not reflected in the redux store causing the loading spinner to disappear when switching views.

Resolves #872 

## How this PR fixes it
Adds a new `PendingStatus.SIGNING` which receives the pending `signerAddress` as payload.
The `txQueueSlice` middleware will update the pending status once the pending signature is returned by the tx service queue.

## How to test it
1. Queue any tx is a 2/n safe
2. add the second signature without executing the tx
3. witness the new "Signing" status which is persisted when switching to the history tab and back

## Analytics changes
None

## Screenshots
pendingSignature

### CODE REVIEW

File: src/hooks/useTransactionStatus.ts [hunk 1]
```diff
@@ -20,6 +20,7 @@ const STATUS_LABELS: Record<TxLocalStatus, string> = {
   [PendingStatus.SUBMITTING]: 'Submitting',
   [PendingStatus.PROCESSING]: 'Processing',
   [PendingStatus.INDEXING]: 'Indexing',
+  [PendingStatus.SIGNING]: 'Signing',
```
Comment (schmanu) [inline src/hooks/useTransactionStatus.ts:23]: Question for reviewer: Is `Signing` a good label for this status?
Or should it be something like `Adding confirmation` or `Indexing confirmation`?

Comment (katspaugh) [reply src/hooks/useTransactionStatus.ts:23]: I think it's a good name!

File: src/hooks/useTxPendingStatuses.ts [hunk 2]
```diff
@@ -75,6 +77,7 @@ const useTxPendingStatuses = (): void => {
             status,
             txHash: 'txHash' in detail ? detail.txHash : undefined,
             groupKey: 'groupKey' in detail ? detail.groupKey : undefined,
+            signerAddress: `signerAddress` in detail ? detail.signerAddress : undefined,
```
Comment (katspaugh) [inline src/hooks/useTxPendingStatuses.ts:80]: Why back-tick quotes?

**Review by katspaugh — APPROVED** [review]
Looks good!

It's basically the same logic we have for when an executed tx is being indexed, right?

**Review by iamacook — COMMENTED** [review]
Have you tested this with on-chain signatures?

**Comment by schmanu** [comment]
> Looks good!
> 
> It's basically the same logic we have for when an executed tx is being indexed, right?

Yes it's using the our `pendingTxsSlice` and similar to how we remove successfully executed transactions once they appear in the history we remove the new 'SIGNING' state once the missing signature is added.

File: src/services/tx/txSender.ts [hunk 3]
```diff
@@ -217,7 +217,10 @@ export const dispatchTxProposal = async (
     throw error
   }
 
-  txDispatch(txId ? TxEvent.SIGNATURE_PROPOSED : TxEvent.PROPOSED, { txId: proposedTx.txId })
+  txDispatch(txId ? TxEvent.SIGNATURE_PROPOSED : TxEvent.PROPOSED, {
+    txId: proposedTx.txId,
+    signerAddress: txId ? sender : undefined,
```
Comment (iamacook) [inline src/services/tx/txSender.ts:222]: Should we not always dispatch with `sender`?

**Comment by francovenica** [comment]
Issue:
For safes 3/3 or higher, during the "signing" status the amount of signatures goes to 3/3 even if that signature is just the 2nd one, so it should show 2/3 during that signature
Tested this on the main branch and doens't happen there, so is just this PR.

signing

**Comment by schmanu** [comment]
> > Issue: For safes 3/3 or higher, during the "signing" status the amount of signatures goes to 3/3 even if that signature is just the 2nd one, so it should show 2/3 during that signature Tested this on the main branch and doens't happen there, so is just this PR.
> 
> Imo, this should show 1/3 whilst "Signing" until the backend confirmed the user is no longer a `missingSigner`, then show 2/3.

I didn 't really touch that logic but with the new state it would be very consistent to only show the confirmations once they are reflected by the tx service. I will look into it.

**Comment by schmanu** [comment]
> > Issue: For safes 3/3 or higher, during the "signing" status the amount of signatures goes to 3/3 even if that signature is just the 2nd one, so it should show 2/3 during that signature Tested this on the main branch and doens't happen there, so is just this PR.
> 
> Imo, this should show 1/3 whilst "Signing" until the backend confirmed the user is no longer a `missingSigner`, then show 2/3.

@iamacook I removed the the overwrites for the number of confirmations to remove this bug.

**Comment by francovenica** [comment]
Looks good now. The amount of signatures updates after the singing status is done
