### PR TITLE
Fix: analytics events

### LINKED ISSUE #471: Analytics tracking
## Bug description
This list was taken from the Analytics > events folder in the web core repo and are the tracks that have issues (missing or dubious).
Anything in the code that had a comment of "not implemented" in any way was skipped

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby
 - Env: https://web-core.pages.dev/

## Steps to reproduce
 1. Make sure to have the Analytics checkbox marked in preferences

## Obtained result
Address book:
Import (button above the table)
Import (The submit button once you loaded)
These 2 buttons have the same track event, except from the button on top of the table has a undefined eventLabel and the other actually has it defined.

- Assets:
Differing Tokens: I couldn't find this trigger, is it sent in another action? there is no comment in the code

- Create safe form:
The "Continue" and "Back" button trigger the same event as the modals like "Send funds" with the "Category: 'modals'". Is this correct? This is also for the Load safe form

The Create safe, once is done, trigger 3 events that look exaclty the same
image

"Get Started" and "go to safe" are events in the code, but they are not used because after the safe is created it goes straight to the safe, there is no more "get started" button

- Modals:
* [x] Opening the "Adv parameters" display triggers an event, so I assume there should be one for Transaction Details".  (fixed in #474)

- Overview:
Home (the top left icon) triggers the "Welcome home" event, but that logo no longer takes to the welcome page at all.

- Settings:
In the code there is "Owner" and "Treshold" events that don't have a trigger because there is no longer "owners" and "treshold" in the submenu button in settings.

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #471

## How this PR fixes it

Adds missing events and removes wrong/unused events.

### CODE REVIEW

File: src/components/address-book/ImportDialog/index.tsx [hunk 1]
```diff
@@ -86,12 +84,18 @@ const ImportDialog = ({ handleClose }: { handleClose: () => void }): ReactElemen
             setZoneHover(false)
             setError(undefined)
 
-            const message = abOnUploadValidator(result)
+            // Remove empty rows
+            const cleanResult = {
+              ...result,
+              data: result.data.filter(hasEntry),
+            }
```
Comment (katspaugh) [inline src/components/address-book/ImportDialog/index.tsx:91]: Added this because some editors automatically add an empty new line at the end of file. We should just ignore them.

File: src/components/tx/TxStepper/useTxStepper.ts [hunk 2]
```diff
@@ -32,12 +31,10 @@ export const useTxStepper = ({ steps, initialData, initialStep, onClose, onFinis
 
   const handleNext = () => {
     setActiveStep((prevActiveStep) => prevActiveStep + 1)
-    trackEvent({ category: MODALS_CATEGORY, action: lastStep ? 'Submit' : 'Next' })
   }
 
   const handleBack = () => {
     setActiveStep((prevActiveStep) => prevActiveStep - 1)
-    trackEvent({ category: MODALS_CATEGORY, action: firstStep ? 'Cancel' : 'Back' })
```
Comment (katspaugh) [inline src/components/tx/TxStepper/useTxStepper.ts:40]: My understanding is, these two events weren't in safe-react and weren't documented.
I think they are two generic to track. It's gonna be hard to analyze them. Removed.

Comment (iamacook) [reply src/components/tx/TxStepper/useTxStepper.ts:40]: The equivalent [is in `safe-react`](https://github.com/safe-global/safe-react/blob/bccf8b3259c5b175fd61972bea49c0261327a0ba/src/routes/safe/components/Transactions/helpers/TxModalWrapper/index.tsx#L333). It can be used in funnels.

Comment (katspaugh) [reply src/components/tx/TxStepper/useTxStepper.ts:40]: True, will restore them then. The only problem the stepper is also used by Create Safe as per Franco's findings.

Comment (iamacook) [reply src/components/tx/TxStepper/useTxStepper.ts:40]: They are useful there. We can analyse if a certain step is 'successful', i.e. the user doesn't tend to go back.

Comment (katspaugh) [reply src/components/tx/TxStepper/useTxStepper.ts:40]: They might be, but the name is "modals"

Comment (iamacook) [reply src/components/tx/TxStepper/useTxStepper.ts:40]: I see. Perhaps we should create a new category for "generic" values then?

Comment (katspaugh) [reply src/components/tx/TxStepper/useTxStepper.ts]: I think the way to go would be to pass `category: 'create-safe'` and keep `modals` for modals.

Comment (iamacook) [reply src/components/tx/TxStepper/useTxStepper.ts]: Sounds good!

**Review by iamacook — APPROVED** [review]

File: src/components/tx/TxStepper/useTxStepper.ts (hunk 2 above)
Comment (katspaugh) [reply src/components/tx/TxStepper/useTxStepper.ts]: Added a todo in the issue.
