### PR TITLE
Fix: single transaction skeleton

### LINKED ISSUE #1671: Skeleton loaders around Safe
## Bug description
Pages that don't have a skeleton:
- Assets (Tokens and NFTs)
- Address Book (Not sure)
- Apps
- Settings (Not sure)

@liliya-soroka if you can help with further investigation of states thats needed skeletons
If design is needed let me know, but the skeletons thats already exist is great for the reference.

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #1671

The final piece of #1671 – a skeleton for the single tx page.

Screenshot 2023-02-28 at 12 21 47

## How this PR fixes it
I've replaced the circular loader with a skeleton in an expanded accordion.
Also changed the links from the dashboard queue widget to open individual txs instead of the entire queue. "View all" still links to the queue.

### CODE REVIEW

File: src/components/transactions/TxListItem/ExpandableTransactionItem.tsx [hunk 1]
```diff
@@ -53,4 +53,22 @@ export const ExpandableTransactionItem = ({
   )
 }
 
+export const TransactionSkeleton = () => (
+  <>
+    <Box pt="20px" pb="4px">
+      <Skeleton variant="text" width="35px" />
+    </Box>
```
Comment (DiogoSoaress) [inline src/components/transactions/TxListItem/ExpandableTransactionItem.tsx:60]: This Skeleton is unnecessary in the Single Tx because there is no label

**Review by DiogoSoaress — APPROVED** [review]
Works well!
Left one comment though

File: src/components/transactions/TxListItem/ExpandableTransactionItem.tsx (hunk 1 above)
Comment (katspaugh) [reply src/components/transactions/TxListItem/ExpandableTransactionItem.tsx:60]: For queued transactions, there's always a label. I guess it's arbitrary if we want to have it or not.

**Comment by katspaugh** [comment]
Tested again, works as expected. ✅
