### PR TITLE
Fix: redirect from a bare safe address URL

### LINKED ISSUE #604: Redirect ends "404 -Page Not Found" when navigating to `/<chain>:<safe_address>`
## Bug description
The app flicks until ending up in a "404 - Page Not Found" when navigating to https://web-core.pages.dev/rin:0x3bCF8Ab8ae461c0A19668B06461a1e209256394e

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0x3bCF8Ab8ae461c0A19668B06461a1e209256394e

## Expected result
Goes to the safe Dashboard

## Obtained result
404 - Page Not Found

## Screenshots
Screenshot 2022-09-21 at 19 13 49

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #604 

## How this PR fixes it
It was a regression after I added _redirects. The `/` should remain in the URL.

### CODE REVIEW

File: src/hooks/usePathRewrite.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ export const useQueryRewrite = (): boolean => {
     const [, pathSafe] = currentPath.match(re) || []
 
     if (pathSafe) {
-      const newPath = currentPath.replace(re, '')
+      const newPath = currentPath.replace(pathSafe, '')
```
Comment (katspaugh) [inline src/hooks/usePathRewrite.ts:61]: This is the actual fix. It should replace just the address part, not the whole regex. This is how it had been before I broke it in #570.

**Review by DiogoSoaress — APPROVED** [review]
