### PR TITLE
fix: Use eth_sign when connected via WC

### LINKED ISSUE #503: Wallet connect: can not sign if the wallet is connected via WC
The same issue for the wallets connected via WC:
Steps:
1. open Metamask on the mobile device
2. connect Metamask to the safe via WC
3. try to sign tx
Current result: The error appears, and signing is not possible 

Image

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #503 

## How this PR fixes it

Uses `eth_sign` when signing a transaction via WalletConnect

## How to test it

1. Open the Safe
2. Connect to the safe via mobile MM app
3. Create/Sign a transaction
4. Observe no error
5. Observe a window popping up on the mobile MM app

### CODE REVIEW

File: src/components/tx/SignOrExecuteForm/index.tsx [hunk 1]
```diff
@@ -101,7 +101,8 @@ const SignOrExecuteForm = ({
   const onSign = async (): Promise<string> => {
     const [connectedWallet, createdTx, provider] = assertSubmittable()
 
-    const shouldEthSign = isHardwareWallet(connectedWallet) || isSafeMobileWallet(connectedWallet)
+    const shouldEthSign =
+      isHardwareWallet(connectedWallet) || isSafeMobileWallet(connectedWallet) || isWalletConnect(connectedWallet)
```
Comment (iamacook) [inline src/components/tx/SignOrExecuteForm/index.tsx:105]: I suggest we create a helper for this with a brief note as to why each requires it. Would be nice to add a test case for it as well.

**Review by iamacook — APPROVED** [review]
