### PR TITLE
fix: Reuse amount validation for spending limits

### LINKED ISSUE #1654: Spending Limits: amount is too small error in case of wrong token decimals
## Bug description
Spending Limits: amount is too small error in case of wrong token decimals
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Go to spending limits as an owner
 2.  start a new spending limit creation with USDC as an erc20 token ( token decimal = 6)
 3. enter 0.100000000005 as an amount 
 Current result: Amount is too small error is displayed instead of 

## Expected result
the same error as on the send funds modal
image

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #1654 

## How this PR fixes it

- Adds decimal validation to the amount input in `SpendingLimitForm`

## How to test it

1. Open a Safe
2. Create a new Spending Limit
5. Amount can't have too little or too many decimals

## Screenshots
Screenshot 2023-03-01 at 17 09 44

### CODE REVIEW

File: src/components/settings/SpendingLimits/NewSpendingLimit/steps/SpendingLimitForm.tsx [hunk 1]
```diff
@@ -36,16 +37,6 @@ type Props = {
   onSubmit: (data: NewSpendingLimitData) => void
 }
 
-export const _validateSpendingLimit = (val: string, decimals?: number) => {
-  // Allowance amount is uint96 https://github.com/safe-global/safe-modules/blob/master/allowances/contracts/AlowanceModule.sol#L52
```
Comment (iamacook) [inline src/components/settings/SpendingLimits/NewSpendingLimit/steps/SpendingLimitForm.tsx:40]: There is a contractual upper limit to allowance amounts so we need to keep this as it's possible to have more assets than the limit, i.e. uint96 + 1.

File: src/components/settings/SpendingLimits/NewSpendingLimit/steps/SpendingLimitForm.tsx [hunk 2]
```diff
@@ -110,11 +113,26 @@ export const SpendingLimitForm = ({ data, onSubmit }: Props) => {
...
+              }}
               required
               {...register('amount', {
                 required: true,
-                validate: (val) =>
-                  validateAmount(val) || _validateSpendingLimit(val, selectedToken?.tokenInfo.decimals),
+                validate: (val) => {
+                  const decimals = selectedToken?.tokenInfo.decimals
+                  return (
+                    validateLimitedAmount(val, decimals, totalAmount.toString()) || validateDecimalLength(val, decimals)
```
Comment (iamacook) [inline src/components/settings/SpendingLimits/NewSpendingLimit/steps/SpendingLimitForm.tsx:133]: It should also be possible to set spending limits higher than that of the total owned.

**Review by iamacook — APPROVED** [review]

**Comment by francovenica** [comment]
LGTM
spending limit stuff
