### PR TITLE
fix: Persist stepper data when going back in create/load safe

### LINKED ISSUE #768: Owners and threshold are not persisted on Safe creation flow
## Bug description
On the Safe creation flow, after setting an owners policy. If the user goes back one step to rename the Safe, the previously set Owners and threshold are gone.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to Safe creation
 2. Add more owners and change the threshold on step 3
 3. Go back to rename the Safe
 4. Back to step 3 the previously setup is lost

## Expected result
Owners and threshold are persisted across steps

## Obtained result
Previously setup is lost

## Screenshots
owners and threshold gone

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #768 

## How this PR fixes it

- Extends `useTxStepper` to optionally update step data when going back
- Updates data in create/load safe forms when going back
- Fixes an issue where owner AddressBook names would overwrite a newly typed name in create/load safe forms

## How to test it

1. Open the Safe
2. Create a new Safe
3. Input data in every screen and press back and continue
4. Observe that the data is persisted
5. Load an existing Safe
6. Change data in every screen and press back and continue
7. Observe that the data is persisted
8. Change the name of an existing owner that has an AB entry and press back/continue
9. Observe that the newly typed name is shown instead of the AB name

### CODE REVIEW

File: src/components/tx/TxStepper/useTxStepper.ts [hunk 1]
```diff
@@ -46,9 +47,20 @@ export const useTxStepper = ({
     trackEvent({ category: eventCategory, action: lastStep ? 'Submit' : 'Next' })
   }
 
-  const handleBack = () => {
+  const handleBack = (data?: unknown) => {
     setActiveStep((prevActiveStep) => prevActiveStep - 1)
     trackEvent({ category: eventCategory, action: firstStep ? 'Cancel' : 'Back' })
+
+    if (data) {
```
Comment (katspaugh) [inline src/components/tx/TxStepper/useTxStepper.ts:54]: Nice solution 👍

**Review by iamacook — APPROVED** [review]

**Review by schmanu — APPROVED** [review]
Looks good to me :)
