### PR TITLE
fix: placeholder when no apps found

### LINKED ISSUE #836: Safe apps search `PagePlaceholder`
## What is the feature about

Adding placeholder when no Safe apps are found after search.

## The list of requirements

- Include `PagePlaceholder` when filtered `filteredApps.length === 0` (`props.img` must react to dark mode).

## Designs/sketches

image

## Links

- [Figma design](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=1%3A7)
- Removed in [this commit](https://github.com/safe-global/web-core/pull/818/commits/c277f75c5e701a68badef2b103e0e4bd818939d5) from rebrancing feedback PR.

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #836

## How this PR fixes it

Adds placeholder when no searchs apps are found.

## How to test it

Open Safe and search for apps that don't exist. Observe the placeholder with working WalletConnect button (across networks).

## Screenshots

image

image

### CODE REVIEW

**Comment by katspaugh** [comment]
Code looks good 👍 
We should probably add a max-width to PagePlaceholder, it's hard to read the text when it's stretched so far. Maybe max 600px or so?

File: src/components/safe-apps/SafeAppList.tsx [hunk 1]
```diff
@@ -28,6 +37,22 @@ const SafeAppList = () => {
...
+    }
+
+    return {
+      pathname: AppRoutes.apps,
+      query: {
+        safe: router.query.safe,
+        appUrl: wc.url,
+      },
+    }
+  }, [allSafeApps, router.query.safe])
```
Comment (katspaugh) [inline src/components/safe-apps/SafeAppList.tsx:54]: I would extract this into a hook `useWalletConnectApp` like I did for the Transaction Builder in NewTxModal.

**Comment by iamacook** [comment]
> Code looks good 👍 We should probably add a max-width to PagePlaceholder, it's hard to read the text when it's stretched so far. Maybe max 600px or so?

Adjusted accordingly:

image

File: src/components/safe-apps/SafeAppsSearchPlaceholder.tsx [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+import PagePlaceholder from '../common/PagePlaceholder'
+import AddCustomAppIcon from '@/public/images/apps/add-custom-app.svg'
+import { AppRoutes } from '@/config/routes'
+import { SafeAppsTag } from '@/config/constants'
+import { useSafeApps } from '@/hooks/safe-apps/useSafeApps'
+
+const useWCAppLink = (): LinkProps['href'] => {
+  const router = useRouter()
+  const { allSafeApps } = useSafeApps()
+  const app = allSafeApps.find((app) => app.tags?.includes(SafeAppsTag.TX_BUILDER))
```
Comment (katspaugh) [inline src/components/safe-apps/SafeAppsSearchPlaceholder.tsx:16]:
```suggestion
  const app = allSafeApps.find((app) => app.tags?.includes(SafeAppsTag.WALLET_CONNECT))
```
