### PR TITLE
fix: strikethrough other transactions on hover

### LINKED ISSUE #699: Tx list - "Transaction will be replaced" status missing
## Bug description
When two tx have the same nonce and one of them is ready to be executed, hovering on it should strike the text of the other and show in the status "transaction will be replaced"

## Environment
 - Browser: any
 - Wallet: any
 - Chain: any

## Steps to reproduce
 1. Go to a safe you own
 2. Queue any type of transaction
 3. Queue its rejection (so now 2 tx have the same nonce)
 4. Fully sign one of the tx
 5. Hover the Execute button in the fully signed tx (do not click it, just hover)

## Expected result
The other tx has its text grayed out and with a strike line. The status changes to "Transaction will be replaced"

## Obtained result
No changes in the other tx

## Screenshots
Web core:
image

For comparison, how it looks in safe-react:
image

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #699

## How this PR fixes it

When hovering over the execution icon or button on conflicting transactions, the `id` of that transaction is saved. Other transactions in the group are strikedthrough in reference to this (and pending transactions of the same group).

A new "Transaction will be replaced" status has been added as well.

## How to test it

Create a group of conflicting transactions. Observe when hovering over the execute icon or button that the other transactions in the group are strikethrough. When one of them is execute and is pending, the other remain strikedthrough.

### Hovering

image

image

image

image

### Executing

image

### CODE REVIEW

File: src/components/transactions/ExecuteTxButton/index.tsx [hunk 1]
```diff
@@ -31,19 +33,41 @@ const ExecuteTxButton = ({
...
   return (
     <>
       <Track {...TX_LIST_EVENTS.EXECUTE}>
         {compact ? (
           <Tooltip title="Execute" arrow placement="top">
             <span>
-              <IconButton onClick={onClick} color="primary" disabled={isDisabled} size="small">
+              <IconButton
+                onClick={onClick}
+                onMouseOver={onMouseOver}
```
Comment (katspaugh) [inline src/components/transactions/ExecuteTxButton/index.tsx:52]: `onMouseOver` fires several times when hovering. You probably want `onMouseEnter`.

File: src/hooks/useTransactionStatus.ts [hunk 2]
```diff
@@ -1,9 +1,13 @@
+import { WillReplaceContext } from '@/components/transactions/GroupedTxListItems/WillReplaceProvider'
 import { useAppSelector } from '@/store'
 import { PendingStatus, selectPendingTxById } from '@/store/pendingTxsSlice'
 import { isSignableBy } from '@/utils/transaction-guards'
 import { TransactionSummary, TransactionStatus } from '@gnosis.pm/safe-react-gateway-sdk'
+import { useContext } from 'react'
 import useWallet from './wallets/useWallet'
 
+const REPLACEMENT_STATUS = 'Transaction will be replaced'
```
Comment (katspaugh) [inline src/hooks/useTransactionStatus.ts:9]: I realize it's tempting to just hardcode an exception for this status, but I think we should include it in the STATUS_LABELS and have a proper type for it.

File: src/components/transactions/GroupedTxListItems/WillReplaceProvider.tsx [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+export const WillReplaceContext = createContext<{
+  willReplace: string[]
+  setWillExecute: Dispatch<SetStateAction<string | undefined>>
+}>({
+  willReplace: [],
+  setWillExecute: () => {},
+})
+
+// Used for striking through transactions that will be replaced
+export const WillReplaceProvider = ({
```
Comment (katspaugh) [inline src/components/transactions/GroupedTxListItems/WillReplaceProvider.tsx:16]: The `willReplace` terminology isn't very clear out of context (pun not intended).

I would call the provider `ReplaceTxHoverProvider` or some such (like the BatchHoverProvider).

Instead of `willReplace` in the return value: 'replacedTxIds`.

**Review by katspaugh — CHANGES_REQUESTED** [review]

File: src/components/transactions/GroupedTxListItems/WillReplaceProvider.tsx [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+  groupedListItems,
+  children,
+}: {
+  groupedListItems: Transaction[]
+  children: ReactElement
+}): ReactElement => {
+  const [willExecute, setWillExecute] = useState<string>()
+  const pendingTxs = useAppSelector(selectPendingTxs)
+
+  const willReplace = useMemo(() => {
```
Comment (usame-algan) [inline src/components/transactions/GroupedTxListItems/WillReplaceProvider.tsx:26]: `willExecute` and `willReplace` sound like they describe boolean variables. I would suggest something like `pendingItem` and `disabledItems`.

**Review by usame-algan — CHANGES_REQUESTED** [review]

File: src/hooks/useTransactionStatus.ts (hunk 2 above)
Comment (iamacook) [reply src/hooks/useTransactionStatus.ts]: I've added `WILL_BE_REPLACED` to the `TxLocalStatus` type as it otherwise maps to `enum`s. Let me know what you think.

**Comment by usame-algan** [comment]
There is a slight overlap with the new status now. I suggest we increase the min-width of that column [from 140px to 170px](https://github.com/safe-global/web-core/blob/5153317098746fab3d0b79bedd1410fcde7644be/src/components/transactions/TxSummary/styles.module.css#L14)
Screenshot 2022-09-28 at 13 42 06

File: src/hooks/useTransactionStatus.ts [hunk 5]
```diff
@@ -1,10 +1,12 @@
+import { ReplaceTxHoverContext } from '@/components/transactions/GroupedTxListItems/ReplaceTxHoverProvider'
 import { useAppSelector } from '@/store'
 import { PendingStatus, selectPendingTxById } from '@/store/pendingTxsSlice'
 import { isSignableBy } from '@/utils/transaction-guards'
 import { TransactionSummary, TransactionStatus } from '@gnosis.pm/safe-react-gateway-sdk'
+import { useContext } from 'react'
 import useWallet from './wallets/useWallet'
 
-type TxLocalStatus = TransactionStatus | PendingStatus
+type TxLocalStatus = TransactionStatus | PendingStatus | 'WILL_BE_REPLACED'
```
Comment (katspaugh) [inline src/hooks/useTransactionStatus.ts:9]: Can you please put it in a var so that we don't have to type the string again on line 36?

E.g.
```
const ReplacedStatus = 'WILL_BE_REPLACED'
...
const STATUS_LABELS = {
  [ReplacedStatus]: 'Transaction will be replaced',
}
...
return STATUS_LABELS[ReplacedStatus]
```

File: src/components/transactions/GroupedTxListItems/ReplaceTxHoverProvider.tsx [hunk 6]
```diff
@@ -0,0 +1,53 @@
+import { createContext, useMemo, useState, type Dispatch, type ReactElement, type SetStateAction } from 'react'
+import type { Transaction } from '@gnosis.pm/safe-react-gateway-sdk'
+
+import { useAppSelector } from '@/store'
+import { selectPendingTxs } from '@/store/pendingTxsSlice'
+
+export const ReplaceTxHoverContext = createContext<{
+  replacedTxIds: string[]
+  setExecutoryTxId: Dispatch<SetStateAction<string | undefined>>
```
Comment (katspaugh) [inline src/components/transactions/GroupedTxListItems/ReplaceTxHoverProvider.tsx:9]: Suggestion: `setReplacingTxId`

**Review by katspaugh — APPROVED** [review]

**Review by usame-algan — APPROVED** [review]
