### PR TITLE
Fix: MUI CSS cache for SSG

### LINKED ISSUE #680: Visual issues on UI on the first load
## Bug description
When entering on the web application for the first time some styles of the page are not fully loaded causing visual inconsistencies for about 2-3 seconds.

## Environment
 - Browser: Any
 - Wallet: Any
 - Chain: Any

## Steps to reproduce
Open an incognito private window and access the [address book](https://web-core.pages.dev/rin:0x91dB860c37E83dab0A4A005E209577E64c61EEfA/address-book) or [settings](https://web-core.pages.dev/rin:0x91dB860c37E83dab0A4A005E209577E64c61EEfA/settings/setup)

## Expected result
No visual issues.
## Obtained result
Visual issues for about 2-3 seconds.

## Screenshots
Captura de pantalla 2022-09-27 a las 10 02 42
Captura de pantalla 2022-09-27 a las 10 37 33

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #680

## How this PR fixes it

I've copied this example: https://github.com/mui/material-ui/tree/master/examples/nextjs-with-typescript

Basically restoring what @yagopv already did once.

The MUI theme CSS is now embedded into the pre-built HTML files.

### CODE REVIEW

File: src/pages/_document.tsx [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+import Document, { Html, Head, Main, NextScript, DocumentContext } from 'next/document'
+import createEmotionServer from '@emotion/server/create-instance'
+import createEmotionCache from '@/utils/createEmotionCache'
+
+export default class WebCoreDocument extends Document {
+  render() {
+    return (
+      <Html lang="en">
+        <Head>
+          <meta name="emotion-insertion-point" content="" />
```
Comment (usame-algan) [inline src/pages/_document.tsx:14]:
```suggestion
        <Head>
          <title>Safe</title>
          <meta name="emotion-insertion-point" content="" />
```
Getting a warning that `title` is required but missing.

**Review by usame-algan — APPROVED** [review]
💯

File: src/pages/_document.tsx (hunk 1 above)
Comment (katspaugh) [reply src/pages/_document.tsx:14]: Removed it again, it shows a lint error with it.
