### PR TITLE
Fix: default wallet when none are enabled

### LINKED ISSUE #1596: 8 wallets are displayed by default when no selected wallets in the config service
8 wallets are displayed by default when no selected wallets in the config service
1. add new network to the config service 
2. all wallets should be off for the network
3.  switch to the new network on web-core
4. click connect 
Current result: 

Image

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #1596

## How this PR fixes it

When all wallets are disabled, we pass an empty array to onboard, but it needs at least one wallet. So I made it return the "injected" wallet as a default.

## How to test it
Cello has currently 0 wallets enabled in the staging config.

### CODE REVIEW

File: src/hooks/wallets/wallets.ts [hunk 1]
```diff
@@ -67,9 +67,13 @@ export const getSupportedWallets = (chain: ChainInfo): WalletInit[] => {
   if (window.Cypress && CYPRESS_MNEMONIC) {
     return [e2eWalletModule(chain.rpcUri)]
   }
-  return Object.entries(WALLET_MODULES)
-    .filter(([key]) => isWalletSupported(chain.disabledWallets, key))
-    .map(([, module]) => module())
+  const enabledWallets = Object.entries(WALLET_MODULES).filter(([key]) => isWalletSupported(chain.disabledWallets, key))
+
+  if (enabledWallets.length === 0) {
+    return [WALLET_MODULES.INJECTED()]
```
Comment (iamacook) [inline src/hooks/wallets/wallets.ts:73]: MetaMask can be disabled:

image

We should probably return an empty array here, as well as filter the "recommended injected wallets" in `getRecommendedInjectedWallets`. What do you think?

Comment (katspaugh) [reply src/hooks/wallets/wallets.ts:73]: I think you're thinking too much into it. In practice, no chain will have all wallets disabled, and defaulting to the injected wallet is a quick and pragmatic solution w/o adding too many conditions IMHO.

Comment (iamacook) [reply src/hooks/wallets/wallets.ts:73]: We should remove MetaMask from the list of wallets that can be disabled when we eventually [remove the "legacy" wallet names](https://github.com/safe-global/web-core/issues/713) then.

**Review by iamacook — APPROVED** [review]

**Comment by liliya-soroka** [comment]
@katspaugh , I have a problem with the Ledger connection , only in the PR. No such problem on staging 
image

**Comment by liliya-soroka** [comment]
verified
can be merged
