### PR TITLE
fix: Add overview widget to step 1 in safe creation

### LINKED ISSUE #1209: [Safe Creation] Safe preview widget missing in step one
## Bug description
In the Figma design, in the 1st step that can only be seen if the user is not connected to the app, there is a Safe preview widget to not leave the right side empty. That widget is missing currently

## Environment
 - Browser: Any
 - Env: https://creation.web-core.pages.dev/new-safe/create
 - Ticket: https://github.com/safe-global/web-core/issues/864

## Steps to reproduce
 1. Go to the 1st step disconnected

## Screenshots
Expected:
image

Current:
image

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #1209 

## How this PR fixes it

- Displays the overview widget in step 1 with a message 

## How to test it

1. Open the new safe creation flow
2. Disconnect wallet
3. The overview widget is visible

## Screenshots

Screenshot 2022-11-21 at 15 06 17

### CODE REVIEW

File: src/components/new-safe/OverviewWidget/index.tsx [hunk 1]
```diff
@@ -26,12 +26,20 @@ const OverviewWidget = ({ safeName }: { safeName: string }): ReactElement | null
...
+            </div>
+          ))
+        ) : (
+          <div className={css.row}>
+            <Typography variant="body2" color="border.main" textAlign="center" width={1}>
+              Connect your wallet to continue
+            </Typography>
           </div>
-        ))}
+        )}
```
Comment (iamacook) [inline src/components/new-safe/OverviewWidget/index.tsx:42]: Let's move this ternary to `rows[0]`. There is already the `wallet` check there.

Comment (usame-algan) [reply src/components/new-safe/OverviewWidget/index.tsx:42]: It would be nice but after trying, it will still display the other values if they exist which makes the message "Connect your wallet to continue" a bit confusing.
Screenshot 2022-11-21 at 15 20 06

**Review by iamacook — APPROVED** [review]
