### PR TITLE
fix: create Safe App share URL in `useEffect`

### LINKED ISSUE #1644: getShareSafeAppUrl references `window` outside of an effect
It might cause hydration issues. We should move it to a `useEffect`.

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #1644

## How this PR fixes it

Creation of the Safe App share URL now happens inside a `useEffect`.

## How to test it

- Ensure Safe Apps share URL is created correctly.
- Ensure the share page of the Safe App opens and does not redirect away.

## Checklist
* [x] I've tested the branch on mobile 📱
* [x] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/pages/index.tsx [hunk 1]
```diff
@@ -13,6 +13,10 @@ const IndexPage: NextPage = () => {
   const safeAddress = safe || lastSafe
 
   useIsomorphicEffect(() => {
+    if (router.pathname !== AppRoutes.index) {
+      return
+    }
```
Comment (iamacook) [inline src/pages/index.tsx:18]: This was running on the share page.

**Review by schmanu — APPROVED** [review]

**Comment by francovenica** [comment]
LGTM
