### PR TITLE
Fix: redirect old tx id URLs

### LINKED ISSUE #1869: Old transaction id links don't work
We used to have transaction deep links in this format:
```
{chain prefix}:{safe_address}/transactions/{client_gateway_transaction_id}
```
And this format is still used by the mobile app.

The new format is
```
/transactions/tx?safe={chain prefix}:{safe_address}&id={client_gateway_transaction_id}
```

The old format should redirect to the new format. As of now it's giving a 404.

Also the share link in the tx details should be updated to use the Safe address as a query param.

See https://github.com/safe-global/safe-ios/issues/2480#issuecomment-1509376303

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #1869

## How this PR fixes it
I've added a condition to rewrite paths containing `/transactions/(something-that-is not-in-the-static-routes)` to `/transactions/tx?id=...`.

## How to test it

Open a link like this:

https://fix_tx_url--webcore.review-web-core.5afe.dev/eth:0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6/transactions/multisig_0xA77DE01e157f9f57C7c4A326eeE9C4874D0598b6_0x102f72ce18d977a144ddef78c1f35a3102d04e94cc39e3e59d874874f22a7ec2

It should redirect to the new format.

### CODE REVIEW

File: src/pages/404.tsx [hunk 1]
```diff
@@ -1,20 +1,30 @@
...
-    const newPath = pathname.replace(re, '') || '/'
+    let newPath = pathname.replace(re, '') || '/'
+    let newSearch = search ? '&' + search.slice(1) : ''
+
+    // TxId used to be in the path, rewrite it to the query
+    if (newPath.startsWith(AppRoutes.transactions.index)) {
+      const isStaticPath = Object.values(AppRoutes.transactions).some((route) => route === newPath)
+      if (!isStaticPath) {
+        const txId = newPath.match(/\/transactions\/([^/]+)/)?.[1]
+        newPath = '/transactions/tx'
```
Comment (iamacook) [inline src/pages/404.tsx:21]:
```suggestion
        newPath = AppRoutes.transactions.tx
```

**Review by iamacook — APPROVED** [review]
Small suggestion, otherwise LGTM

File: src/pages/404.tsx (hunk 1 above)
Comment (katspaugh) [reply src/pages/404.tsx]: 🏋️🧠

File: src/pages/404.tsx [hunk 2]
```diff
@@ -1,20 +1,30 @@
...
 import { useRouter } from 'next/router'
+import { AppRoutes } from '@/config/routes'
 
 // Rewrite the URL to put the Safe address into the query.
-const getRedirectUrl = (): string | undefined => {
-  if (typeof location === 'undefined') return
-
+export const _getRedirectUrl = (location: Location): string | undefined => {
   const { pathname, search } = location
   const re = /^\/([^/]+?:0x[0-9a-f]{40})/i
```
Comment (usame-algan) [inline src/pages/404.tsx:9]: Nit: We have a simliar expression in our url utils file called `prefixedAddressRe`. I would suggest moving this there or at least giving it a more descriptive name. I assume it also describes prefixed addresses but less restrictive when it comes to the shortname prefix?

**Review by usame-algan — APPROVED** [review]
👍

File: src/pages/404.tsx (hunk 2 above)
Comment (katspaugh) [reply src/pages/404.tsx:9]: I wouldn't touch this at this time, so as not to break anything that isn't related to the tx id accidentally.

Comment (katspaugh) [reply src/pages/404.tsx:9]: A good mini-refactoring idea tho, feel free to make a tech debt issue.

**Comment by liliya-soroka** [comment]
Verified
