### PR TITLE
fix: filter by start/end of day + offset tx list timezones

### LINKED ISSUE #499: Filter - Date sets 1 day earlier
## Bug description
Setting a date in the From or To input will show as 1 day earlier after filtering.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Rinkeby

## Steps to reproduce
 1. Go to any safe, history tab
 2. Set the From or To field (or both) to any date, like 20/8/2022 and filter
 3. Open the filter again and see the dates saved

## Expected result
The dates are the ones that you filtered before

## Obtained result
Both dates are 1 day earlier, in this case it would be 19/8/2022
Note that the filter works fine (it will search taking in account the date used for filter, 20/8/2022 in this case). the issue is just the date it shows after filtering

## Screenshots
date

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #499 & #500

## How this PR fixes it

Date filters are now based on local start/end of day. Transaction list date labels are offset according to local timezone.

Note: duplicate date labels occur when same-day transactions span across infinite scroll pages:

image

### Date filters
1. Filtering outgoing transactions from 01-24.08.2022 on `rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808` should show the correct period. Reducing it until 19.08 should include those transactions on the 19th.
2. Apply a date filter. Observe when opening the filter form again that the date is the same as that originally entered.

### Date labels
Observe that date labels within the past 24 hours are in hours, within 60 days are from day start and then specific times.

## Screenshots
filter
image

### CODE REVIEW

**Comment by DiogoSoaress** [comment]
It seems we still need some tweak here as the filter does not display all the transactions from the `to` day
Screenshot 2022-09-06 at 10 28 47

_filter applied_
Screenshot 2022-09-06 at 10 29 09

**Comment by DiogoSoaress** [comment]
It seems we still need some tweak here as the filter does not display all the transactions from the `to` day
Screenshot 2022-09-06 at 10 28 47

_filter applied_
Screenshot 2022-09-06 at 10 32 33

File: src/utils/tx-history-filter.ts [hunk 1]
```diff
@@ -64,12 +65,14 @@ export const txFilter = {
...
 
   parseFormData: ({ type, ...formData }: TxFilterFormState): TxFilter => {
-    const DATE_FORMAT = 'yyyy-MM-dd'
-
     const filter: TxFilter['filter'] = _omitNullish({
       ...formData,
-      execution_date__gte: formData.execution_date__gte ? format(formData.execution_date__gte, DATE_FORMAT) : undefined,
-      execution_date__lte: formData.execution_date__lte ? format(formData.execution_date__lte, DATE_FORMAT) : undefined,
+      execution_date__gte: formData.execution_date__gte
+        ? startOfDay(formData.execution_date__gte).toISOString()
```
Comment (usame-algan) [inline src/utils/tx-history-filter.ts:71]: I think depending on the timezone, this can still result in the previous day being selected. E.g. if the user is in GMT+2, the start of the day is being selected at 0:00:00 hours and with the conversion through `toISOString` it would result in the previous day because 2 hours are subtracted.

Comment (iamacook) [reply src/utils/tx-history-filter.ts:71]: My debugging shows the same. I'll revisit this later today.

File: src/utils/tx-history-filter.ts [hunk 2]
```diff
@@ -9,8 +9,9 @@ import {
 } from '@gnosis.pm/safe-react-gateway-sdk'
 import type { operations } from '@gnosis.pm/safe-react-gateway-sdk/dist/types/api'
 import type { ParsedUrlQuery } from 'querystring'
-import format from 'date-fns/format'
-import { isSameDay } from 'date-fns'
+import endOfDay from 'date-fns/endOfDay'
+import isSameDay from 'date-fns/isSameDay'
+import startOfDay from 'date-fns/startOfDay'
```
Comment (DiogoSoaress) [inline src/utils/tx-history-filter.ts:14]:
```suggestion
import { endOfDay, isSameDay, startOfDay } from 'date-fns'
```

File: package.json [hunk 3]
```diff
@@ -14,7 +14,7 @@
     "lint:fix": "next lint --fix",
     "prettier": "prettier -w \"{src,cypress,mocks,scripts}/**/*.{ts,tsx,css,js}\"",
     "fix": "yarn lint:fix && ts-prune && yarn prettier",
-    "test": "DEBUG_PRINT_LIMIT=30000 jest",
+    "test": "cross-env TZ=CET DEBUG_PRINT_LIMIT=30000 jest",
```
Comment (DiogoSoaress) [inline package.json:17]: why do we need this change?

File: package.json [hunk 4]
```diff
@@ -23,7 +23,7 @@
     "generate-types:spendingLimit": "typechain --target ethers-v5 --out-dir src/types/contracts ./node_modules/@gnosis.pm/safe-modules-deployments/dist/assets/**/*.json",
     "generate-types": "yarn generate-types:safeDeployments && yarn generate-types:spendingLimit",
     "postinstall": "yarn generate-types && yarn css-vars",
-    "analyze": "ANALYZE=true yarn build",
+    "analyze": "cross-env ANALYZE=true yarn build",
```
Comment (DiogoSoaress) [inline package.json:26]: also here?

File: src/utils/tx-history-filter.ts (hunk 2 above)
Comment (iamacook) [reply src/utils/tx-history-filter.ts:14]: This modularises the imports.

File: package.json (hunk 3 above)
Comment (iamacook) [reply package.json:17]: This sets the timezone of Jest.

File: package.json (hunk 4 above)
Comment (iamacook) [reply package.json:26]: Windows doesn't inject env variables unless we use `cross-env`.

File: package.json (hunk 3 above)
Comment (DiogoSoaress) [reply package.json:17]: and the `cross-env` allows it to be injected in Windows machines 👍

File: src/utils/tx-history-filter.ts (hunk 1 above)
Comment (iamacook) [reply src/utils/tx-history-filter.ts:71]: After looking into this deeper, it seems as though the trasaction list is returned in UTC but we don't the date labels to match the timezone:

image

**Comment by DiogoSoaress** [comment]
It is missing:
- [ ] dealing with repeated `DATE_LABEL`s when rendering a new page
Screenshot 2022-09-07 at 01 21 16

File: src/utils/tx-history-filter.ts (hunk 1 above)
Comment (usame-algan) [reply src/utils/tx-history-filter.ts:68]: Regarding my original comment, after thinking more about it I think it makes sense to leave it as it is. Even if the query changes to the previous day through the conversion via `toISOString`, it would include results that are on the current day in the local timezone.

File: src/components/common/DatePickerInput/index.tsx [hunk 5]
```diff
@@ -36,7 +35,8 @@ const DatePickerInput = ({
             return 'Invalid date'
           }
 
-          if (disableFuture && isFuture(val)) {
+          // Compare days using `startOfDay` to ignore TZ offset
```
Comment (usame-algan) [inline src/components/common/DatePickerInput/index.tsx:38]:
```suggestion
          // Compare days using `startOfDay` to ignore timezone offset
```

**Review by usame-algan — APPROVED** [review]
