### PR TITLE
Fix: prevent error flashing in SingleTx

### LINKED ISSUE #851: [Single tx] It flashes "Failed to load tx details" before loading the tx details
It should not show an error while loading.

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #851

## How this PR fixes it

`query.id` is undefined at first because the router is client-side only. So the page is pre-generated with an error message.

I removed the handling of a missing query.id. It will just show an infinite loader if you open a page w/o the query param. I think it's fine because why would you open it like this?

### CODE REVIEW

File: src/components/transactions/SingleTx/index.tsx [hunk 1]
```diff
@@ -35,21 +35,23 @@ const SingleTx = () => {
   const [txDetails, txDetailsError] = useAsync<TransactionDetails>(
     () => {
       if (!transactionId) return
-      return getTransactionDetails(chainId, transactionId)
+
+      console.log(safeAddress, transactionId)
```
Comment (iamacook) [inline src/components/transactions/SingleTx/index.tsx:39]: 👀

**Review by iamacook — COMMENTED** [review]
There still seems to be a very brief error shown:

single tx error

**Comment by katspaugh** [comment]
@iamacook fixed, it was because safeAddress is async, it was undefined on first request (and also it would be doing two requests).

**Review by iamacook — APPROVED** [review]
