### PR TITLE
fix: Allow editing gas fees for spending limit transactions

### LINKED ISSUE #1345: [Spending Limit] It's not possible to edit gas parameters
## Bug description

When creating a spending limit transaction the overall estimated fee is visible but it is not possible to edit any of the values (gasLimit, maxFeePerGas, ...)

## Steps to reproduce
 1. Go to a Safe
 2. Create a spending limit transaction
 3. Observe that it is not possible to edit advanced parameters in the review screen

## Expected result

Screenshot 2022-12-12 at 11 59 52

## Obtained result

Screenshot 2022-12-12 at 12 00 20

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #1345 

## How this PR fixes it

- Doesn't disable the gas fee accordion even if the nonce is undefined

## How to test it

1. Open the Safe
2. Create a new spending limit transaction
3. Observe that the "Estimated Fee" Accordion is clickable and opens
4. Observe being able to edit gas fee params

## Screenshots
Screenshot 2022-12-14 at 14 58 10

### CODE REVIEW

File: src/components/tx/AdvancedParams/AdvancedParamsForm.tsx [hunk 1]
```diff
@@ -84,11 +84,13 @@ const AdvancedParamsForm = ({ params, ...props }: AdvancedParamsFormProps) => {
         <form onSubmit={onFormSubmit}>
           <DialogContent>
             <Grid container spacing={2}>
-              <Grid item xs={12}>
-                <Typography variant="body1" fontWeight={700}>
-                  Safe transaction
-                </Typography>
-              </Grid>
+              {(params.nonce !== undefined || !!params.safeTxGas) && (
```
Comment (usame-algan) [inline src/components/tx/AdvancedParams/AdvancedParamsForm.tsx:87]: Added this condition so that the title is only shown if there is either a nonce or safeTxGas field

**Review by iamacook — APPROVED** [review]

**Comment by iamacook** [comment]
Can confirm that it is now possible to edit the transaction details of spending limit transactions.

spending limit
