### PR TITLE
fix: fallback to `chainId` of `wallet`

### LINKED ISSUE #1554: Use the chain the wallet is connected to as fallback
When the URL doesn't contain a chain id (e.g. when visiting the index page, or the welcome page), and a wallet is connected, use the wallet's network as the app chain.

E.g.
* User opens the `/welcome` page
* Connects their wallet, which is connected to Polygon
* The app should switch to Polygon

The current behavior falls back to a default chain instead (mainnet on prod and goerli on dev).

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #1554

## How this PR fixes it

`useChainId` returns the `chainId` of the connected wallet if no `chainId` is present in the URL or cached from the last session.

## How to test it

1. Open a "non-`chainId`" URL in an Incognito window (e.g. `/welcome`).
2. Ensure the wallet is connected to a chain that is present in the environment chain configuration and connect the wallet.
3. Observe the chain in the top right matches that of the wallet.

---

1. Open a "non-`chainId`" URL in an Incognito window (e.g. `/welcome`).
2. Ensure the wallet is connected to a chain that is NOT present in the environment chain configuration and connect the wallet.
3. Observe the chain in the top right is the default fallback, Mainnet on prod. or Goerli on dev.

### CODE REVIEW

File: src/hooks/useChainId.ts [hunk 1]
```diff
@@ -44,7 +46,15 @@ export const useUrlChainId = (): string | undefined => {
...
-  return urlChainId || session.lastChainId || defaultChainId
+  const wallet = useWallet()
+  const chains = useChains()
+
+  const fallbackChainId =
+    wallet?.chainId && chains?.configs.some(({ chainId }) => chainId === wallet.chainId)
+      ? wallet.chainId
+      : defaultChainId
+
+  return urlChainId || session.lastChainId || fallbackChainId
```
Comment (katspaugh) [inline src/hooks/useChainId.ts:57]: I would define the wallet chainId as a separate thing and fall back in this order:
```
  return urlChainId || walletChainId || session.lastChainId || fallbackChainId
```

Comment (usame-algan) [reply src/hooks/useChainId.ts:57]: Is `fallbackChainId` and `walletChainId` the same thing?

Comment (iamacook) [reply src/hooks/useChainId.ts]: I've inverted the order and added tests to cover it.

Comment (iamacook) [reply src/hooks/useChainId.ts]: > Is fallbackChainId and walletChainId the same thing?

In my previous commit, `fallbackChainId` was either that of the `wallet` or from `defaultChainId`. I've changed it in accordance with the first suggestion. Wdyt?

**Review by katspaugh — APPROVED** [review]
Thanks! 👍

**Comment by katspaugh** [comment]
Tested, it correctly sets the app network with the current wallet network if you're on a page w/o a Safe address or `?chain=` in the URL. ✅ 
It even changes the app network when you change the wallet network.
