### PR TITLE
fix: wrong message in safe creation relay

### LINKED ISSUE #1864: [Relaying] Wallet confirmation request in Safe creation
## Bug description

"Please confirm the transaction with your wallet." shown when relaying a Safe creation.

## Environment
 - Browser: Firefox
 - Wallet: MetaMask
 - Chain: Gnosis Chain

## Steps to reproduce
 1. Create a Safe via the relay but navigate away during creation.
 2. Return to the Safe creation and observe the request in the stepper (even though relaying).

## Expected result

The request is not shown.

## Obtained result

The request is shown.

## Screenshots

image

### PR DESCRIPTION
**Pull request by DiogoSoaress**
## What it solves

Resolves #1864

## How this PR fixes it
- Initiates the relay "Status" page in the PROCESSING status instead of AWAITING.

Also tackled 2 small fixes:
- Loading skeleton in dashboard's Relaying widget
- `/welcome` page card buttons

## How to test it
On create Safe through relaying, the "Please confirm the transaction with your wallet." should not appear anymore.

## Screenshots
_Skeleton_
Screenshot 2023-04-27 at 11 21 24

_/welcome cards_
Screenshot 2023-04-27 at 17 03 06

## Checklist
* [ ] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/components/dashboard/Relaying/index.tsx [hunk 1]
```diff
@@ -50,22 +50,24 @@ const Relaying = () => {
...
-                  {relays.remaining} of {limit}
-                </Typography>
-              ) : (
-                <Skeleton className={css.chipSkeleton} variant="rounded" />
-              )}
-            </Box>
+            {relays !== undefined ? (
+              <Box
+                className={classnames(css.relayingChip, {
+                  [css.unavailable]: relays && relays.remaining === 0,
```
Comment (iamacook) [inline src/components/dashboard/Relaying/index.tsx:56]:
```suggestion
                  [css.unavailable]: relays.remaining === 0,
```

File: src/components/dashboard/Relaying/index.tsx [hunk 2]
```diff
@@ -50,22 +50,24 @@ const Relaying = () => {
...
+                })}
+              >
+                <SvgIcon component={InfoIcon} fontSize="small" />
+                {relaysError ? (
+                  <Typography fontWeight={700}>{limit} per hour</Typography>
+                ) : (
+                  <Typography fontWeight={700}>
+                    {relays?.remaining} of {limit}
```
Comment (iamacook) [inline src/components/dashboard/Relaying/index.tsx:64]:
```suggestion
                    {relays.remaining} of {limit}
```

File: src/components/new-safe/create/steps/StatusStep/index.tsx [hunk 3]
```diff
@@ -39,7 +38,12 @@ export const CreateSafeStatus = ({ data, setProgressColor }: StepRenderProps<New
   const isWrongChain = useIsWrongChain()
   const isConnected = wallet && !isWrongChain
 
-  const { handleCreateSafe } = useSafeCreation(pendingSafe, setPendingSafe, status, setStatus, data.willRelay)
+  // The willRelay flag can come from the previous step or from local storage
+  const willRelay = data.willRelay || pendingSafe?.willRelay
+  const initialStatus = willRelay ? SafeCreationStatus.PROCESSING : SafeCreationStatus.AWAITING
```
Comment (iamacook) [inline src/components/new-safe/create/steps/StatusStep/index.tsx:43]: The initial status is also referenced in `useSafeCreation` on line 146-147. What do you think about creating a helper for this? e.g.

```ts
const getInitialCreationStatus = (willRelay: boolean) => willRelay ? SafeCreationStatus.PROCESSING : SafeCreationStatus.AWAITING
```

File: src/components/dashboard/Relaying/index.tsx [hunk 4]
```diff
@@ -50,22 +50,24 @@ const Relaying = () => {
...
-                <Typography fontWeight={700}>{limit} per hour</Typography>
-              ) : relays?.remaining !== undefined ? (
-                <Typography fontWeight={700}>
-                  {relays.remaining} of {limit}
-                </Typography>
-              ) : (
-                <Skeleton className={css.chipSkeleton} variant="rounded" />
-              )}
-            </Box>
+            {relays !== undefined ? (
```
Comment (iamacook) [inline src/components/dashboard/Relaying/index.tsx:53]: Nit: I'd suggest keeping unrelated changes like this in separate PRs in the future. This initially confused me.

File: src/components/new-safe/create/steps/ReviewStep/index.tsx [hunk 5]
```diff
@@ -79,7 +79,7 @@ const ReviewStep = ({ data, onSubmit, onBack, setStep }: StepRenderProps<NewSafe
 
     const safeAddress = await computeNewSafeAddress(provider, props)
 
-    setPendingSafe({ ...data, saltNonce, safeAddress })
+    setPendingSafe({ ...data, saltNonce, safeAddress, willRelay })
```
Comment (iamacook) [inline src/components/new-safe/create/steps/ReviewStep/index.tsx:82]: Just noticed that this and `onSubmit` are both using the same data structure. Instead of spreading in both, lets extract this to a variable.

**Review by iamacook — COMMENTED** [review]
Nice work! Just tested this working for Safe creation and cached Safe creation.

It would be nice to add another test to cover this as well.

File: src/components/dashboard/Relaying/index.tsx (hunk 4 above)
Comment (DiogoSoaress) [reply src/components/dashboard/Relaying/index.tsx:53]: Sorry, I tried to use the PR description to give context to the unrelated changes. Will mind it for future ref

File: src/components/new-safe/create/steps/StatusStep/useSafeCreation.ts [hunk 6]
```diff
@@ -140,8 +140,13 @@ export const useSafeCreation = (
     setIsWatching(false)
   }, [isWatching, pendingSafe, web3ReadOnly, setStatus, dispatch])
 
+  // Create or monitor Safe creation
   useEffect(() => {
-    if (status !== SafeCreationStatus.AWAITING) return
+    if (
+      (!willRelay && status !== SafeCreationStatus.AWAITING) ||
+      (willRelay && status !== SafeCreationStatus.PROCESSING)
```
Comment (iamacook) [inline src/components/new-safe/create/steps/StatusStep/useSafeCreation.ts:147]:
```suggestion
      status !== getInitialCreationStatus(willRelay)
```

**Comment by usame-algan** [comment]
Its hard to test this at the moment because we still trigger multiple transactions. I suggest to wait for https://github.com/safe-global/web-core/pull/1883 to be merged before moving this to QA.

**Comment by francovenica** [comment]
Looks good. The message "confirm with your wallet" is not longer present when using the relayer and it IS present if there are no more relayer attempts to use.

The skeleton for the relayer counter looks good
The aligment of the buttons in the Welcome page cards is good too

**Review by katspaugh — APPROVED** [review]

**Review by usame-algan — APPROVED** [review]
LGTM 👍
