### PR TITLE
fix: only use address book/known names

### LINKED ISSUE #749: [Settings-module] Addressbook name has the priority for address names on UI
## Bug description
Addressbook name has the priority for address names on UI or make sure that the same name is used in the modules table and on the remove module review screen
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain:rinkeby

## Steps to reproduce
 1. make sure that a spending limits module is enabled in your safe
 2. add the spending limit module address in the address book with a custom name
 3. go to the settings->modules
 Current result: you will see that the address has a "spending limits module" name ( probably from the back-end known addresses list

4. click remove spending limit module
Current result: on the review screen you will see the address name from the addressbook

## Expected result
Make sure that the address book name has priority over the known address name or any other sourth.

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #749, #775 & #755

## How this PR fixes it

- 749/775: We no longer hardcode any module names, including "Unknown module".
- 755: Contract interactions in the transaction list return the address book entry name if it is present as their type.

## How to test it

- 749/775: Ensure the spending limit or other module is enabled on your Safe and observe that they have no name.
- 755: Interact with a contract then add it's address to your address book. Observe the transaction list type now returns the address book name

## Screenshots

module name

image

### CODE REVIEW

File: src/components/settings/SafeModules/index.tsx [hunk 1]
```diff
@@ -18,14 +14,6 @@ const NoModules = () => {
   )
 }
 
-const getModuleName = (chainId: string, address: string): string => {
-  if (sameAddress(getSpendingLimitModuleAddress(chainId), address)) {
-    return 'Spending limit module'
-  }
```
Comment (katspaugh) [inline src/components/settings/SafeModules/index.tsx:24]: Wasn't this quite useful?

File: src/hooks/useTransactionType.ts [hunk 2]
```diff
@@ -84,20 +85,14 @@ const getTxType = (tx: TransactionSummary): TxType => {
...
       }
     }
   }
 }
-
-export const useTransactionType = (tx: TransactionSummary): TxType => {
-  return useMemo(() => {
-    return getTxType(tx)
-  }, [tx])
-}
```
Comment (DiogoSoaress) [inline src/hooks/useTransactionType.ts:103]: won't we lose performance for dismissing this memoization?

File: src/components/settings/SafeModules/index.tsx (hunk 1 above)
Comment (katspaugh) [reply src/components/settings/SafeModules/index.tsx:24]: Maybe we could initialize the AB with some preset address like this?

Comment (iamacook) [reply src/components/settings/SafeModules/index.tsx:24]: I like the idea but I think it's best backend decide the known addresses. It means there isn't a populated address book from the get go as well. What do you think?

File: src/hooks/useTransactionType.ts (hunk 2 above)
Comment (iamacook) [reply src/hooks/useTransactionType.ts:103]: The performance increased seemed neglibile when looking at the dependency array but I'll put it back.

**Review by DiogoSoaress — APPROVED** [review]
Thanks! It LGTM 👍

File: src/components/settings/SafeModules/index.tsx (hunk 1 above)
Comment (katspaugh) [reply src/components/settings/SafeModules/index.tsx:24]: Backend having it would be best of course.

Comment (liliya-soroka) [reply src/components/settings/SafeModules/index.tsx:24]: we only need somebody with permissions on prod to add the module to the known addresses list

**Comment by JagoFigueroa** [comment]
All of the fixes look good to me, thanks! Moving the related tickets to QA done.
