### PR TITLE
fix: Use custom safeTxGas for simulations

### LINKED ISSUE #1294: Custom safeTxGas is not used for simulations
## Bug description

The transaction simulation is always using the default `safeTxGas`.

## Steps to reproduce
 1. Go to a 1.1.1 safe
 2. Create a transaction
 3. Observe that a `safeTxGas` value is visible in the params
 4. Press Simulate
 5. Check that the transaction data contains the same `safeTxGas` amount
 6. Open the params and change the `safeTxGas` value
 7. Press Simulate again
 8. Observe that the transaction data still contains the default `safeTxGas` amount

## Screenshots

Screenshot 2022-11-30 at 18 45 27
Screenshot 2022-11-30 at 18 45 43

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #1294 

## How this PR fixes it

- Uses the updated `tx` object for simulations

## How to test it

1. Open a 1.1.1 safe
2. Create a new transaction
3. Simulate
4. Observe that Tenderly receives the initially estimated safeTxGas
5. Change the safeTxGas
6. Simulate
7. Observe that Tenderly receives the custom safeTxGas

### CODE REVIEW

File: src/components/tx/SignOrExecuteForm/index.tsx [hunk 1]
```diff
@@ -238,7 +238,7 @@ const SignOrExecuteForm = ({
 
         <TxSimulation
           gasLimit={advancedParams.gasLimit?.toNumber()}
-          transactions={safeTx}
+          transactions={tx}
```
Comment (katspaugh) [inline src/components/tx/SignOrExecuteForm/index.tsx:241]: Oh, damn, I can see why this was easy to miss. Maybe we should rename `safeTx` to `_originalTx` or something?

**Review by katspaugh — APPROVED** [review]

**Comment by francovenica** [comment]
Looks good. I compared with current prod and this PR, and I could verify that tenderly is receiving the edited safeTxGas set by the user.

image
image
