### PR TITLE
fix: Replacement modal button alignment on mobile

### LINKED ISSUE #1357: [mobile view] Replace tx form is not mobile friendly
Regression issue in the 1.2.0 rc     
   5. Regarding transaction replacement modal, presentation is a bit off when viewing it from a mobile device (video is from the browser but in mobile resolution  I was able to reproduce this as well on my Iphone 13 pro):

https://user-images.githubusercontent.com/92332710/207279666-f907907e-9dc3-4a65-a6a9-10ed79073684.mp4

_Originally posted by @JagoFigueroa in https://github.com/safe-global/web-core/issues/1341#issuecomment-1348041780_

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #1357 

## How this PR fixes it

- Aligns the replacement modal buttons on smaller screens to fit the viewport

## How to test it

1. Open the Safe
2. Replace an existing transaction
3. Observe that the buttons are aligned
4. Reduce the screen width
5. Observe that all buttons are still visible

## Screenshots
Screenshot 2022-12-13 at 14 11 09

### CODE REVIEW

File: src/components/tx/modals/NewTxModal/ReplacementModal.tsx [hunk 1]
```diff
@@ -51,11 +51,6 @@ const btnWidth = {
   },
 }
 
-const flexDirection: SystemProps['flexDirection'] = {
```
Comment (iamacook) [inline src/components/tx/modals/NewTxModal/ReplacementModal.tsx:54]: `SystemProps` no longer needs to be imported.

**Review by iamacook — APPROVED** [review]

**Comment by liliya-soroka** [comment]
Verified
