### PR TITLE
fix: Safe version/upgrade button improvements

### LINKED ISSUE #1530: [Safe upgrade] Add info on why users should upgrade
## 1. Add a help link/tooltip near the upgrade button
Screenshot 2023-01-12 at 12 44 42
Add a little help link here:  "ℹ️ Why should I upgrade?"
We don't have a help article yet, so it could just show a tooltip saying:

```
Update now to take advantage of new features and the highest security standards available.
You will need to confirm this update just like any other transaction.
```

@ennisjo will soon create a help article we can link.

## 2. Indicate up-to-date Safes
If Safe info says `UP_TO_DATE`, show "✅ Latest version" next to the version.

Screenshot 2023-01-12 at 12 43 40

## 3. Show the upgrade notification only once for a given Safe
If the user closed it, remember it and don't show it next time for that Safe unless 90 days passed.

### PR DESCRIPTION
**Pull request by abheektripathy**
## What it solves

Resolves #1530

Tasks-
- [x] Add a help link
- [x] If safe's upgraded, show latest version.
- [ ] Upgrade notification

## How this PR fixes it
Added a conditional that checks the `Safe's` state, if it's `UP_TO_DATE` shows Latest Version or else a link with  the tooltip as mentioned.

## How to test it
go to the settings page to verify your safe version.

## Screenshots

Screenshot 2023-02-01 at 5 40 16 PM

Screenshot 2023-02-01 at 5 58 04 PM

(for this screenshot i hardcoded the safe version to be `OUTDATED`)

### CODE REVIEW

**Comment by abheektripathy** [comment]
@iamacook if the article's ready, lemme know. I'll link that.

**Review by iamacook — COMMENTED** [review]
Thank you for your contribution, @abheektripathy - it looks very cool so far!

I have a few small suggestions.

File: src/components/settings/ContractVersion/index.tsx [hunk 1]
```diff
@@ -42,6 +45,27 @@ export const ContractVersion = ({ isGranted }: { isGranted: boolean }) => {
...
+              ✅ Latest version
+            </Typography>
+          </Typography>
+        ) : (
+          <Tooltip
+            title="Update now to take advantage of new features and the highest security standards available.
+You will need to confirm this update just like any other transaction."
+            placement="right-end"
+          >
+            <Link sx={{ fontSize: '14px' }} href="">
```
Comment (katspaugh) [inline src/components/settings/ContractVersion/index.tsx:63]: > `sx={{ fontSize: '14px' }}`

@iamacook do you know if we can use `variant="body2"` here or something similar?

File: src/components/settings/ContractVersion/index.tsx [hunk 2]
```diff
@@ -42,6 +45,27 @@ export const ContractVersion = ({ isGranted }: { isGranted: boolean }) => {
           Unsupported contract
         </Typography>
       )}
+      <>
+        <br></br>
+        <br></br>
+        {isUpdated! ? (
+          <Typography variant="body1" fontWeight={400}>
+            <Typography variant="body1" fontWeight={400}>
+              ✅ Latest version
```
Comment (katspaugh) [inline src/components/settings/ContractVersion/index.tsx:54]: For the checkmark, we need to use some suitable icon from MUI.

File: src/components/settings/ContractVersion/index.tsx (hunk 1 above)
Comment (iamacook) [reply src/components/settings/ContractVersion/index.tsx:63]: Yes, `Link` [accepts `variant`](https://mui.com/material-ui/api/link/#props).

File: src/components/settings/ContractVersion/index.tsx [hunk 3]
```diff
@@ -42,6 +45,27 @@ export const ContractVersion = ({ isGranted }: { isGranted: boolean }) => {
           Unsupported contract
         </Typography>
       )}
+      <>
+        <br></br>
+        <br></br>
+        {isUpdated! ? (
+          <Typography variant="body1" fontWeight={400}>
```
[the remark this answers is not in the document]
Comment (abheektripathy) [reply src/components/settings/ContractVersion/index.tsx:52]: hi, as im using a conditional here, instead of adding margin to both the elements differently how about I warp it inside a div and give it some top-margin.
```suggestion
 <div style={{ marginTop: 15 }}>
        {needsUpdate ? (
          <Typography>✅ Latest version</Typography>
```

File: src/components/settings/ContractVersion/index.tsx [hunk 4]
```diff
@@ -42,6 +45,27 @@ export const ContractVersion = ({ isGranted }: { isGranted: boolean }) => {
...
+            </Typography>
+          </Typography>
+        ) : (
+          <Tooltip
+            title="Update now to take advantage of new features and the highest security standards available.
+You will need to confirm this update just like any other transaction."
+            placement="right-end"
+          >
+            <Link sx={{ fontSize: '14px' }} href="">
+              ℹ️ Why should I upgrade?
```
Comment (katspaugh) [inline src/components/settings/ContractVersion/index.tsx:64]: For the info icon, we've used this in other places:
```
import InfoIcon from '@/public/images/notifications/info.svg'

        <SvgIcon
          component={InfoIcon}
          inheritViewBox
          fontSize="small"
          color="border"
        />

```

Comment (abheektripathy) [reply src/components/settings/ContractVersion/index.tsx:64]: yes, changed that as well. thanks.

File: src/components/settings/ContractVersion/index.tsx [hunk 5]
```diff
@@ -42,6 +44,24 @@ export const ContractVersion = ({ isGranted }: { isGranted: boolean }) => {
...
         </Typography>
       )}
+      <div style={{ marginTop: 15 }}>
+        {needsUpdate ? (
+          <Tooltip
+            title="Update now to take advantage of new features and the highest security standards available.
+You will need to confirm this update just like any other transaction."
+            placement="right-start"
+          >
+            <Typography variant="body2" style={{ display: 'flex', alignItems: 'center' }}>
```
Comment (iamacook) [inline src/components/settings/ContractVersion/index.tsx:54]: I suggest we keep the text the same size as the other message and use Emption props instead:

```suggestion
            <Typography display="flex" alignItems="center">
```

File: src/components/settings/ContractVersion/index.tsx [hunk 6]
```diff
@@ -42,6 +44,24 @@ export const ContractVersion = ({ isGranted }: { isGranted: boolean }) => {
...
+              <SvgIcon component={InfoIcon} inheritViewBox fontSize="small" color="border" style={{ marginRight: 4 }} />
```
Comment (iamacook) [inline src/components/settings/ContractVersion/index.tsx:55]: By using Emotion's `sx` prop, we get access to the [spacing provided by our theme](https://github.com/safe-global/web-core/blob/dev/src/styles/theme.ts#L64). This is also the spacing we follow for other tooltip icons:

```suggestion
              <SvgIcon
                component={InfoIcon}
                inheritViewBox
                fontSize="small"
                color="border"
                sx={{
                  verticalAlign: 'middle',
                  mr: 0.5,
                }}
              />
```

File: src/components/settings/ContractVersion/index.tsx [hunk 7]
```diff
@@ -42,6 +44,24 @@ export const ContractVersion = ({ isGranted }: { isGranted: boolean }) => {
...
+              Why should I upgrade?
+            </Typography>
+          </Tooltip>
+        ) : (
+          <Typography style={{ display: 'flex', alignItems: 'center' }}>
```
Comment (iamacook) [inline src/components/settings/ContractVersion/index.tsx:60]: As previously metioned regarding Emotion props:

```suggestion
          <Typography display="flex" alignItems="center">
```

File: src/components/settings/ContractVersion/index.tsx [hunk 8]
```diff
@@ -42,6 +44,24 @@ export const ContractVersion = ({ isGranted }: { isGranted: boolean }) => {
...
+            <CheckBoxIcon style={{ color: 'secondary', marginRight: 4 }} /> Latest version
```
Comment (iamacook) [inline src/components/settings/ContractVersion/index.tsx:61]: I suggest we use our primary colour for the checkmark. For which, it needs be applied directly to the icon:

```suggestion
            <CheckBoxIcon color="primary" sx={{ mr: 0.5 }} /> Latest version
```

**Comment by abheektripathy** [comment]
@iamacook thanks for the review, i'll keep in mind to follow this code-style in the future.

**Review by iamacook — APPROVED** [review]

**Comment by francovenica** [comment]
Since an env is not created for these kind of tickets I ask Aaron to show it to me running it locally. 
We checked there and it looks good. The tooltip is there when you hover the "i" icon and the Check of "Latest version" is fine.
We can merge it

We did a quick edit on the type of icon, because the original one (a square with a check) looks like a clickable checkbox:

Some snapshots
image
image


Note: there is a task about the notification that should not show up more than once. That task will be done in another ticket.

**Comment by iamacook** [comment]
Thanks once again for the contribution, @abheektripathy!

> Note: there is a task about the notification that should not show up more than once. That task will be done in another ticket.

I'll merge this PR now as it's UI-focused and reopen the issue for the notification task. (If you'd like to tackle that as well @abheektripathy, you're more than welcome to!)

> ## 3. Show the upgrade notification only once for a given Safe
> If the user closed it, remember it and don't show it next time for that Safe unless 90 days passed.

**Comment by katspaugh** [comment]
Thanks @abheektripathy!
