### PR TITLE
fix: prevent scrollbars on Safe App icons

### LINKED ISSUE #1564: Problem with safe apps logos all over the app
env: dev
where: dashboard, NFTs, safe apps list

Current result: the safe app icon is scrollable 

Image

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #1564

## How this PR fixes it

The `overflow` of the `SafeAppIcon` is not `hidden`.

## How to test it

Open the Safe Apps page and observe no scrollbars on icons.

## Screenshots

image

### CODE REVIEW

File: src/components/safe-apps/SafeAppIcon/index.tsx [hunk 1]
```diff
@@ -4,7 +4,7 @@ const APP_LOGO_FALLBACK_IMAGE = `/images/apps/app-placeholder.svg`
 
 const getIframeContent = (url: string, width: number, height: number): string => {
   return `
-     <body style="margin: 0;">
+     <body style="margin: 0; overflow: hidden;">
```
Comment (katspaugh) [inline src/components/safe-apps/SafeAppIcon/index.tsx:7]: @mikhailxyz display block on the image would make this fix unnecessary.

**Review by katspaugh — APPROVED** [review]

**Review by mikhailxyz — APPROVED** [review]

File: src/components/safe-apps/SafeAppIcon/index.tsx (hunk 1 above)
Comment (mikhailxyz) [reply src/components/safe-apps/SafeAppIcon/index.tsx:7]: absolutely insane stuff

**Review by usame-algan — APPROVED** [review]

**Comment by katspaugh** [comment]
Tested, no scrollbars! ✅
