### PR TITLE
fix: don't scroll wrap in transaction list

### LINKED ISSUE #1914: Single page tx not scrolling for tx with long descriptions
## Bug description
If a tx is too long (multisend with several actions) the transaction only fits in the initial page and doesn't scroll down, only allowing to see the expanded actions in a small page.

## Environment
 - Browser: Any
 - Wallet: Any
 - Chain: Any

## Steps to reproduce
 1. Go to this tx and see that the page doesn't scroll vertically https://safe-web-core.dev.5afe.dev/transactions/tx?safe=gno:0x9DF58F04F3e914ED8D972146401C85313A53FecA&id=multisig_0x9DF58F04F3e914ED8D972146401C85313A53FecA_0xf46cbeeb673201593a8ffae2caa7ffb7877fc3671599c96f6135993271e924b9

## Expected result
It should look like in prod
https://app.safe.global/transactions/tx?safe=gno:0x9DF58F04F3e914ED8D972146401C85313A53FecA&id=multisig_0x9DF58F04F3e914ED8D972146401C85313A53FecA_0xf46cbeeb673201593a8ffae2caa7ffb7877fc3671599c96f6135993271e924b9

## Screenshots
image

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #1914

## How this PR fixes it

The scroll wrapper is not added in the transaction list.

## How to test it

- Open the transaction mentioned in the issue of the PR and observe no scrollbar next to the decoded transaction.
- Batch an NFT transfer and observe that the scrollbar _is_ present next to the decoded transactions in the modal.

## Screenshots

image

## Checklist
* [x] I've tested the branch on mobile 📱
* [x] I've documented how it affects the analytics (if at all) 📊
* [x] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Review by DiogoSoaress — APPROVED** [review]
Can you also remove the gap in the line 93? It's adding an undesired effect I think 
Screenshot 2023-04-27 at 10 25 07

**Comment by iamacook** [comment]
> Can you also remove the gap in the line 93? It's adding an undesired effect I think Screenshot 2023-04-27 at 10 25 07

Good catch. I've removed the `gap`.

File: src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx [hunk 1]
```diff
@@ -90,7 +90,7 @@ export const Multisend = ({
       {!noHeader && <MultisendActionsHeader setOpen={setOpenMap} amount={multiSendTransactions.length} />}
 
       <div className={noHeader && multiSendTransactions.length >= MIN_SCROLL_TXS ? css.scrollWrapper : undefined}>
-        <Box display="flex" flexDirection="column" gap={1}>
+        <Box display="flex" flexDirection="column">
```
Comment (katspaugh) [inline src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx:93]: This gap was there for a reason. It’s needed for the DecodedTx situation. Could you move it there?

Comment (iamacook) [reply src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx]: I've added it when `noHeader` is present:

image

Comment (katspaugh) [reply src/components/transactions/TxDetails/TxData/DecodedData/Multisend/index.tsx]: Thanks!

**Review by katspaugh — APPROVED** [review]
