### PR TITLE
fix: Unhandled exception in useOnboard

### LINKED ISSUE #1783: Unhandled exception in useOnboard
`getAddress` needs to be wrapped in a try-catch and the error properly handled.

Screenshot 2023-03-20 at 08 06 50

https://gnosis.sentry.io/issues/3897265821/?project=6769196&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d

### PR DESCRIPTION
**Pull request by deepaksing**
## What it solves
This PR fixes #1783. Unhandled exception in useOnboard

## How this PR fixes it
In this PR i have added a try catch block that handles any error thrown by the getAddress() function inside the try block. If getAddress() function throws an error, the catch block will be executed and the error will be caught and logged to the console. Then, null will be returned as the value of getConnectedWallet() function.

## Checklist
* [x] I've tested the branch on mobile 📱
* [ ] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

File: src/hooks/wallets/useOnboard.ts [hunk 1]
```diff
@@ -46,12 +46,18 @@ export const getConnectedWallet = (wallets: WalletState[]): ConnectedWallet | nu
...
+    const address = getAddress(account.address)
+    return {
+      label: primaryWallet.label,
+      address,
+      ens: account.ens?.name,
+      chainId: Number(primaryWallet.chains[0].id).toString(10),
+      provider: primaryWallet.provider,
+    }
+  } catch (error) {
+    console.error(error)
```
Comment (iamacook) [inline src/hooks/wallets/useOnboard.ts:59]: We track our errors via Sentry so it would be good to use our logging function here instead. In order to do so, you need add an error message to our [`ErrorCodes`](https://github.com/safe-global/web-core/blob/dev/src/services/exceptions/ErrorCodes.ts) and use `logError` ([example](https://github.com/safe-global/web-core/blob/dev/src/utils/transactions.ts#L186-L188)).

I'd suggest 106, e.g. "106: Failed to get connected wallet".

**Review by iamacook — CHANGES_REQUESTED** [review]
Thank you for putting your time into this, @deepaksing!

We have a test for [`getConnectedWallet`](https://github.com/safe-global/web-core/blob/dev/src/hooks/wallets/useOnboard.test.ts). Could you extend it to cover your changes?

If you need any help, don't hestitate to ask!

File: src/hooks/wallets/useOnboard.ts (hunk 1 above)
Comment (deepaksing) [reply src/hooks/wallets/useOnboard.ts:59]: Ok sure, I will work on that

File: src/hooks/wallets/useOnboard.test.ts [hunk 2]
```diff
@@ -45,4 +45,24 @@ describe('getConnectedWallet', () => {
       chainId: '4',
     })
   })
+
+  it('Failed to get connected wallet', () => {
```
Comment (iamacook) [inline src/hooks/wallets/useOnboard.test.ts:49]: We tend to describe the expectation of a test in it's name.

```suggestion
  it('should return null if the address is invalid', () => {
```

**Review by iamacook — COMMENTED** [review]
I have small suggestion, but otherwise LGTM!

Thanks once again, @deepaksing!

**Review by iamacook — APPROVED** [review]

**Review by katspaugh — APPROVED** [review]
Another great PR, thanks much!
