### PR TITLE
fix: return `null` if no Claiming App on chain

### LINKED ISSUE #1269: [Governance widget] The widget should be displayed only on Ethereum and Goerli for now
## Bug description
The widget should be displayed only on Ethereum and Goerli for now , as it's available only for Ethereum ( main chain with safe tokens) and Goerli ( for testing purposes )
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to dashboard on the Gnosis chain or any other chain ( not ethereum or goerli)

## Expected result
Hide the governance widget on other chains except Ethereum and Goerli

## Screenshots
image

Relates to [[Epic] Governance Visibility#969](https://github.com/safe-global/web-core/issues/969)

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #1269

## How this PR fixes it

If no Claiming App is found (it's not present on the current chain) the Governance section is not rendered.

## How to test it

Open a Safe on Goerli and observe the Governance section. Switch to Gnosis Chain and observe no Governance section.

## Screenshots

image

image

### CODE REVIEW

**Review by schmanu — APPROVED** [review]
Good catch!

File: src/components/dashboard/GovernanceSection/GovernanceSection.tsx [hunk 1]
```diff
@@ -22,6 +22,10 @@ const GovernanceSection = () => {
   const claimingApp = claimingSafeApp?.[0]
   const fetchingSafeClaimingApp = !claimingApp && !errorFetchingClaimingSafeApp
 
+  if (!claimingApp) {
```
Comment (katspaugh) [inline src/components/dashboard/GovernanceSection/GovernanceSection.tsx:25]: What if it's just being loaded? Or errored out?
We want to show both a loading state and an error.

Comment (iamacook) [reply src/components/dashboard/GovernanceSection/GovernanceSection.tsx]: True. I've adjusted it to use the same logic as the token widget.

**Comment by liliya-soroka** [comment]
1. claiming app is displayed instead of the governance widget
image

2. No widget on Goerli ( it should be on Goerli for testing )
image

File: src/components/dashboard/GovernanceSection/GovernanceSection.tsx [hunk 2]
```diff
@@ -13,15 +13,22 @@ import { SafeAppsTag, SAFE_APPS_SUPPORT_CHAT_URL } from '@/config/constants'
...
   const isDarkMode = useDarkMode()
   const theme = isDarkMode ? 'dark' : 'light'
   const { getAllowedFeaturesList } = useBrowserPermissions()
   const [claimingSafeApp, errorFetchingClaimingSafeApp] = useRemoteSafeApps(SafeAppsTag.SAFE_CLAIMING_APP)
   const claimingApp = claimingSafeApp?.[0]
   const fetchingSafeClaimingApp = !claimingApp && !errorFetchingClaimingSafeApp
 
+  if (!getSafeTokenAddress(chainId)) {
+    return null
+  }
```
Comment (katspaugh) [inline src/components/dashboard/GovernanceSection/GovernanceSection.tsx:30]: We could also create a wrapper component on top of GovernanceSection with this check to avoid calling all those hooks needlessly.

**Comment by iamacook** [comment]
> 1. claiming app is displayed instead of the governance widget

We were missing the token address on Goerli. I've added it and this now works on Goerli.

>     2. No widget on Goerli ( it should be on Goerli for testing )

@schmanu, can you confirm why this may be happening? I've tested this working locally fine.

File: src/components/dashboard/GovernanceSection/GovernanceSection.tsx (hunk 2 above)
Comment (iamacook) [reply src/components/dashboard/GovernanceSection/GovernanceSection.tsx:30]: Good point. I'll add this now.

**Review by katspaugh — APPROVED** [review]

**Comment by schmanu** [comment]
Hey @liliya-soroka 

> 1. claiming app is displayed instead of the governance widget

I assume this happened on prod? The governance widgets are not released on prod yet. So the widgets will only work on staging currently. That the claiming app is displayed on prod is expected currently.

**Comment by liliya-soroka** [comment]
Verified
