### PR TITLE
Fix: auto-choose to WalletConnect on mobile

### LINKED ISSUE #871: [Mobile] Wallet connection – use WalletConnect instead of onboard
## Bug description
Most wallets we offer in the onboard popup don't work on mobile, so it's better to just open the WalletConnect popup right away.

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #871

## How this PR fixes it
When the user presses "Connect wallet" on mobile, it automatically pops up the WalletConnect modal instead the onboard modal.

### CODE REVIEW

File: src/components/common/ConnectWallet/WalletDetails.tsx [hunk 1]
```diff
@@ -1,13 +1,23 @@
...
 import useOnboard, { connectWallet } from '@/hooks/wallets/useOnboard'
 import { OVERVIEW_EVENTS } from '@/services/analytics/events/overview'
 import KeyholeIcon from '@/components/common/icons/KeyholeIcon'
 import { trackEvent } from '@/services/analytics'
+import { WalletNames } from '@/utils/wallets'
 
 const WalletDetails = ({ onConnect }: { onConnect?: () => void }): ReactElement => {
   const onboard = useOnboard()
+  const theme = useTheme()
+  const isMobile = useMediaQuery(theme.breakpoints.down('sm'))
```
Comment (iamacook) [inline src/components/common/ConnectWallet/WalletDetails.tsx:13]: Larger tablets won't be deemed as a mobile device. I'd recommend we use `@web3-onboard`'s `getDevice` function instead.

**Review by iamacook — COMMENTED** [review]
It's possible to install plugins on Firefox mobile, e.g. MetaMask. We should probably take this into account. What do you think?

After looking through the code, let's switch `onboard.connectWallet` with `connectWallet` on `SafeAppLanding` in this PR as well.

**Comment by katspaugh** [comment]
I haven't checked mobile browser extensions, but you can go back to the onboard modal if you close the WC modal.

File: src/components/common/ConnectWallet/WalletDetails.tsx (hunk 1 above)
Comment (katspaugh) [reply src/components/common/ConnectWallet/WalletDetails.tsx]: It cannot be imported, AFAICT. I added a simple user agent regex.

Comment (iamacook) [reply src/components/common/ConnectWallet/WalletDetails.tsx]: `getDevice` is indeed exported from a declaration file. You [can use `bowser` directly](https://github.com/safe-global/web-core/blob/dev/src/services/pairing/connector.ts#L32-L34) but the regex seems sufficient for now.

It's somewhat out of scope but we can disable hardware wallets directly, e.g. [Trezor](https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/trezor/src/index.ts#L26) and [Ledger](https://github.com/blocknative/web3-onboard/blob/v2-web3-onboard-develop/packages/ledger/src/index.ts#L116). We could have a standard `filter` we add to all apart from WalletConnect.

**Review by iamacook — APPROVED** [review]
