### PR TITLE
Fix: close connect popup on button click

### LINKED ISSUE #1367: [Mobile] Search bar in WalletConnect popup doesn't work
## Bug description
There's a search function in the WC popup on mobile, it's not clickable atm.

## Steps to reproduce
 1. Open the app on mobile
 2. Click on Connect wallet
 3. Try searching for something
 4. Keyboard isn't appearing

## Note
I already fixed this in the past, but it came back. **Has to do with z-indexes.**

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #1367

## How this PR fixes it

The popover was still open after clicking on Connect, covering the WC popup and blocking input clicks.

### CODE REVIEW

File: src/components/common/ConnectWallet/WalletDetails.tsx [hunk 1]
```diff
@@ -6,7 +6,12 @@ import type { ConnectedWallet } from '@/services/onboard'
 import useConnectWallet from '@/components/common/ConnectWallet/useConnectWallet'
 
 const WalletDetails = ({ onConnect }: { onConnect?: (wallet?: ConnectedWallet) => void }): ReactElement => {
```
Comment (usame-algan) [inline src/components/common/ConnectWallet/WalletDetails.tsx:8]: Checking the places we use `WalletDetails` it looks like `onConnect` doesn't have any params anymore so it could just be `onConnect?: () => void` now.

**Review by usame-algan — APPROVED** [review]
