### PR TITLE
fix: propose transaction with `origin`

### LINKED ISSUE #1035: [Soft release] Transactions created from safe apps not identified by safe apps
## Bug description
Transactions created from safe apps like Tx-builder or Drain account used to be identifiable on the list like transactions that were created from that safe app, with the app logo + app name on the transaction queue or history screens. This is no longer the case with transactions being displayed as standard contract interactions or multisend ones.

## Steps to reproduce
 1. Go to tx-builder or drain account safe apps and create / create + execute any transaction.

## Expected result
[Transaction](https://app.safe.global/gno:0xfca7Da0a0290D7BcBEcD93bE124756fC9B6F8E6A/transactions/tx?id=multisig_0xfca7Da0a0290D7BcBEcD93bE124756fC9B6F8E6A_0xec7f107d303c39c4325a4d21129fafc76201f509694f97e7dc17763f6412558f) has information identifying the app that was created from:
Screenshot 2022-11-02 at 14 58 40

## Obtained result
[Tx from tx-builder](https://app.safe.global/gno:0xfca7Da0a0290D7BcBEcD93bE124756fC9B6F8E6A/transactions/tx?id=multisig_0xfca7Da0a0290D7BcBEcD93bE124756fC9B6F8E6A_0xb7e69d138a978878643c735f40d932419e75925e6024f8305c2e2fbb5227522b) on gnosis chain:
Screenshot 2022-11-02 at 14 58 57

[Tx from Drain account](https://app.safe.global/gor:0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C/transactions/tx?id=multisig_0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C_0xc496d84d6eb583678bfa5c5cf282899295f537a3d54c4a804cc42ea4247c5c3b) on Goerli:
Screenshot 2022-11-02 at 14 59 10

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #1035 

## How this PR fixes it

The `origin` is now proposed with transactions when created via a Safe App.

## How to test it

Create a transaction via the Transaction Builder and observe the logo/name in the transaction list.

## Screenshots
image

### CODE REVIEW

File: src/utils/transactions.ts [hunk 1]
```diff
@@ -184,3 +186,19 @@ export const getQueuedTransactionCount = (txPage?: TransactionListPage): string
...
+
+export const getTxOrigin = (app?: SafeAppData): string | undefined => {
+  if (!app) {
+    return
+  }
+
+  let origin: string | undefined
+
+  try {
+    origin = JSON.stringify({ name: app.name, url: app.url })
```
Comment (usame-algan) [inline src/utils/transactions.ts:198]: Is it documented somewhere what the origin must look like? In safe-react we used `app.id` for the origin instead of a stringified object.

Comment (iamacook) [reply src/utils/transactions.ts:198]: The `origin` must be an object containing the `name` and `url` of the Safe App. [Here it is in `safe-react`](https://github.com/safe-global/safe-react/blob/0d09d940100ac2f0e37b371a6273b51cb490f081/src/routes/safe/components/Transactions/TxList/modals/ApproveTxModal.tsx#L164-L169). I confirmed this with the Safe Apps team yesterday.

**Review by DiogoSoaress — APPROVED** [review]
👍 Looks good and makes sense after knowing that we have to propose the `origin`

**Review by dasanra — APPROVED** [review]

**Comment by JagoFigueroa** [comment]
Espectacular trabajo, thanks!

Screenshot 2022-11-04 at 11 28 07
