### PR TITLE
Fix: pinned Safe Apps per chain

### LINKED ISSUE #814: [Pinned safe apps] Pins performed globally instead of per chain
## Description
We should keep the same behaviour we had in legacy for pinned apps where the users would see their pinned apps per chain and not globally.

## Steps to reproduce
1. Pin a couple of safe apps on the revamp and check local storage.

2. Do the same in legacy for comparison.

## Expected result
Pinned apps stored per chain:
Screenshot 2022-10-05 at 11 32 52

## Obtained result
Pinned apps are stored globally:

Screenshot 2022-10-05 at 11 44 04

### PR DESCRIPTION
**Pull request by katspaugh**
## What it solves

Resolves #814 

## How this PR fixes it
Makes the pinned apps slice an object per chain.

## How to test it
Pin apps on different chain, they should be independent.

## Screenshots
Screenshot 2022-10-18 at 09 22 59

### CODE REVIEW

File: src/components/dashboard/FeaturedApps/FeaturedApps.tsx [hunk 1]
```diff
@@ -23,14 +23,14 @@ const StyledGridItem = styled(Grid)`
 `
 
 export const FeaturedApps = (): ReactElement | null => {
-  const [allApps = [], , isLoading] = useRemoteSafeApps()
```
Comment (mikhailxyz) [inline src/components/dashboard/FeaturedApps/FeaturedApps.tsx:26]: Why replace this with `useSafeApps`? It doesn't look like any non-remote apps are used

**Review by mikhailxyz — APPROVED** [review]

File: src/components/dashboard/FeaturedApps/FeaturedApps.tsx (hunk 1 above)
Comment (katspaugh) [reply src/components/dashboard/FeaturedApps/FeaturedApps.tsx:26]: I grepped, and it was the only place where this hook was used apart from `useSafeApps`.
I think it's better if `useSafeApps` is the only entry to safe apps, and the remote apps hook should remain as a raw fetcher.

Comment (mikhailxyz) [reply src/components/dashboard/FeaturedApps/FeaturedApps.tsx:26]: > I grepped, and it was the only place where this hook was used apart from `useSafeApps`. I think it's better if `useSafeApps` is the only entry to safe apps, and the remote apps hook should remain as a raw fetcher.

`useSafeApps` wasn't meant to be the only entry point, it just happens that most of the places need apps from multiple sources 🤷 If you know that you only need the remote apps, in my opinion, it's better to use the raw hook because `useSafeApps` also requests other resources which are unnecessary in this case
