### PR TITLE
fix: allow using the injected wallet on mobile

### LINKED ISSUE #1878: [Mobile] Enable injected wallet if present
We currently skip the first wallet selection screen on mobile and show the WalletConnect modal right away.
This makes sense in iOS Safari, where there's no and cannot be an injected wallet, but is not desired in a webview of mobile wallet apps. They inject their wallet into the webview.

We shouldn't skip to WalletConnect if window.ethereum is defined.

### PR DESCRIPTION
**Pull request by iamacook**
Note: I do not have access to an iOS device and have only tested this on Android. Faking the UA on desktop shows it working on iOS, but it should still be tested on a physical device.

## What it solves

Resolves #1878

## How this PR fixes it

The presence of `window.ethereum` is also checked before automatically connecting to WalletConnect on mobile. If it _is_ present (an inject wallet exists), no autoconnection occurs.

### _Without_ injected wallet
1. Open the Safe on mobile _without_ an injected wallet installed: on Safari (on iPhone) or on Chrome/Firefox with no extensions (on Android).
2. Click connect and observe the WalletConnect QR immediately shown.

### _With_ injected wallet
1. Open the Safe on mobile _with_ an injected wallet installed: on Chrome/Firefox with the Coinbase/MetaMask extension installed (on Android).
2. Click connect and observe the standard wallet modal shown.

### _Without_ injected wallet

without-injected

### _With_ injected wallet

with-injected

## Checklist
* [x] I've tested the branch on *Android* 📱
* [x] I've documented how it affects the analytics (if at all) 📊
* [ ] I've written a unit/e2e test for it (if applicable) 🧑‍💻

### CODE REVIEW

**Comment by usame-algan** [comment]
Tested it on iOS with the MM app and it gives me options to choose from 👍 

One small issue I noticed is that there seem to be 2 scrollbars present and sometimes it doesn't let me scroll to the bottom of the list.

File: src/hooks/wallets/useOnboard.ts [hunk 1]
```diff
@@ -91,6 +91,14 @@ const trackWalletType = (wallet: ConnectedWallet) => {
 // Detect mobile devices
 const isMobile = () => /iPhone|iPad|iPod|Android/i.test(navigator.userAgent)
 
+// Detect injected wallet
+const hasInjectedWallet = () => {
+  if (typeof window === 'undefined') {
+    return false
+  }
+  return !!window?.ethereum
```
Comment (katspaugh) [inline src/hooks/wallets/useOnboard.ts:99]: Can you please make this one line?

File: src/hooks/wallets/useOnboard.ts [hunk 2]
```diff
@@ -106,8 +114,8 @@ export const connectWallet = async (
 
   isConnecting = true
 
-  // On mobile, automatically choose WalletConnect
-  if (!options && isMobile()) {
+  // On mobile, automatically choose WalletConnect if there is no injected wallet
+  if (!options && isMobile() && !hasInjectedWallet()) {
```
Comment (katspaugh) [inline src/hooks/wallets/useOnboard.ts:118]: LGTM! Did you manage to test it with the coinbase wallet?

Comment (iamacook) [reply src/hooks/wallets/useOnboard.ts:113]: Yes, it works nicely.

**Review by katspaugh — APPROVED** [review]
🚀

**Comment by JagoFigueroa** [comment]
Hola que tal. Working as expected for me for both Android (checked Chrome and Firefox) and iOS (Safari). Only different thing is that the WC pop up itself looks a little bit different for me but the behaviour is the expected one so all bueno from me.

Screenshot 2023-04-20 at 16 18 57
