### PR TITLE
fix: Safe Creation color issues

### LINKED ISSUE #1175: [safe creation]failed creation screen UI issues
## Bug description
There are some diff from the design on the "failed creation" screen:
1. color of the message: the green on the design, the red after implementation
2. the position of the buttons is wrong

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to safe creation flow
 2. go to the last step
 3. click to submit to the wallet for signing
 4. reject in the wallet
## Expected result
image

## Screenshots
image

relates to https://github.com/safe-global/web-core/issues/864

### LINKED ISSUE #1191: [safe creation] Dark theme issues
see details in the - https://5afe.slack.com/archives/C03DAGWJCR5/p1668614769462569

### PR DESCRIPTION
**Pull request by usame-algan**
## What it solves

Resolves #1191 
Resolves #1175

## How this PR fixes it

- Adds a border around hints
- Adds a border around status messages
- Keeps the same progress bar color in dark mode
- Keeps the same estimation background color in dark mode
- Adjusts the button layout on the status view
- Changes the progress bar color and status message background color on error
- Fixes the Safe logo color in the overview widget

## How to test it

1. Go through the new safe creation flow and compare to [feedback](https://5afe.slack.com/archives/C03DAGWJCR5/p1668614769462569)

## Screenshots

Screenshot 2022-11-21 at 12 47 10

Screenshot 2022-11-21 at 12 47 20
Screenshot 2022-11-21 at 12 47 33
Screenshot 2022-11-21 at 12 47 46

### CODE REVIEW

File: src/components/new-safe/CardStepper/index.tsx [hunk 1]
```diff
@@ -1,17 +1,22 @@
+import { useState } from 'react'
+import { Box } from '@mui/system'
 import css from './styles.module.css'
 import { Card, LinearProgress, CardHeader, Avatar, Typography, CardContent } from '@mui/material'
 import type { TxStepperProps } from './useCardStepper'
 import { useCardStepper } from './useCardStepper'
 
 export function CardStepper<StepperData>(props: TxStepperProps<StepperData>) {
+  const [progressColor, setProgressColor] = useState('static.primary')
```
Comment (iamacook) [inline src/components/new-safe/CardStepper/index.tsx:9]: I'd suggest we add a type to this.

**Review by iamacook — APPROVED** [review]

File: src/components/new-safe/CardStepper/index.tsx (hunk 1 above)
Comment (usame-algan) [reply src/components/new-safe/CardStepper/index.tsx:9]: I tried using `keyof Palette` which would allow values like `primary` etc. but it seems Mui doesn't provide a type for the dot syntax. I will add a comment as a research task for the future.

Comment (iamacook) [reply src/components/new-safe/CardStepper/index.tsx:10]: As these are static values used only in one place. What do you think about importing the colour directly instead of extending the palette?
