### PR TITLE
fix: don't adjust timestamps + show exact time on history

### LINKED ISSUE #657: [txs list] Wrong calculation for the N days ago
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD/transactions/queue
image
2. the actual date and time - 
image

Current result: 6 days ago is displayed for the 5 days ago action

## Expected result
Make sure that the valid information is displayed about N days ago in the txs list

### PR DESCRIPTION
**Pull request by iamacook**
## What it solves

Resolves #657 & #673

## How this PR fixes it

- The `timestamp` of a transaction is formatted as is.
- The exact time is shown on the history list.

## How to test it

Open `rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD/transactions/queue` and observe that the queued transaction have valid "n days ago" labels. The exact time will, however, been shown on the history list.

### CODE REVIEW

**Review by usame-algan — APPROVED** [review]

File: src/components/common/DateTime/index.tsx [hunk 1]
```diff
@@ -1,11 +1,16 @@
...
 import { formatDateTime, formatTimeInWords } from '@/utils/date'
+import { useRouter } from 'next/router'
+import { AppRoutes } from '@/config/routes'
 
 const DAYS_THRESHOLD = 60
 
 const DateTime = ({ value }: { value: number }): ReactElement => {
-  const displayExactDate = Math.floor((Date.now() - value) / 1000 / 60 / 60 / 24) > DAYS_THRESHOLD
+  const router = useRouter()
+  const isHistory = router.pathname.includes(AppRoutes.transactions.history)
```
Comment (katspaugh) [inline src/components/common/DateTime/index.tsx:11]: This will match filters as well.

File: src/components/common/DateTime/index.tsx [hunk 2]
```diff
@@ -1,11 +1,16 @@
...
+
+  const displayExactDate = Math.floor((Date.now() - value) / 1000 / 60 / 60 / 24) > DAYS_THRESHOLD || isHistory
```
Comment (katspaugh) [inline src/components/common/DateTime/index.tsx:13]:
```
const isOld = Math.floor((Date.now() - value) / 1000 / 60 / 60 / 24) > DAYS_THRESHOLD
const displayExactDate = isOld || isHistory
```

File: src/components/common/DateTime/index.tsx (hunk 1 above)
Comment (iamacook) [reply src/components/common/DateTime/index.tsx:11]: Yes, filtered results are also historical. This matches `safe-react`.

Comment (katspaugh) [reply src/components/common/DateTime/index.tsx:11]: I guess what I meant is unrelated to this line. I meant that maybe we don't need to show the full date when it's in the date label.

Comment (katspaugh) [reply src/components/common/DateTime/index.tsx:11]: Also why is it `includes` and not just a strict comparison?

Comment (iamacook) [reply src/components/common/DateTime/index.tsx:11]: > I meant that maybe we don't need to show the full date when it's in the date label.

Do you mean something like this?

```tsx
<span>{filter ? formatDateTime(value) : displayExactDate ? formatTime(value) : formatTimeInWords(value)}</span>
```

>Also why is it `includes` and not just a strict comparison?

I'll adjust it.

Comment (katspaugh) [reply src/components/common/DateTime/index.tsx:11]: Filter and queue, yes. They both don't have date labels.

File: src/components/common/DateTime/index.tsx [hunk 3]
```diff
@@ -1,20 +1,25 @@
...
+  const isHistory = router.pathname === AppRoutes.transactions.history
+
+  const isOld = Math.floor((Date.now() - value) / 1000 / 60 / 60 / 24) > DAYS_THRESHOLD
+
+  const displayExactDate = isOld || isHistory
 
   return (
     <Tooltip title={displayExactDate ? '' : formatDateTime(value)} placement="top">
-      <span>{displayExactDate ? formatDateTime(value) : formatTimeInWords(getRelevantTimestamp(value))}</span>
+      <span>{filter ? formatDateTime(value) : displayExactDate ? formatTime(value) : formatTimeInWords(value)}</span>
```
Comment (katspaugh) [inline src/components/common/DateTime/index.tsx:22]: What about the queue?

Comment (iamacook) [reply src/components/common/DateTime/index.tsx:22]: As per https://github.com/safe-global/web-core/issues/673, the queue will use "textual" time up until the threshold.

Comment (iamacook) [reply src/components/common/DateTime/index.tsx:22]: The queue and filter have no date labels.

- As per #673, the queue should show "n days ago" until the `DAYS_THRESHOLD` is met and the history show "Jan 1, 1970 - 00:00:00 AM".
- However, as per your suggestion, the history should use "00:00:00 AM" as it has date labels and the filter use "Jan 1, 1970 - 00:00:00 AM" as it doesn't.

Comment (katspaugh) [reply src/components/common/DateTime/index.tsx:22]: Yes. From your code however, I see the following logic:
* If filter, show full date-time
* If history or over 60 days, show time when over 60 days
* If queue, it will show **only time** when over 60 days, otherwise "N days ago"

**Review by katspaugh — APPROVED** [review]

**Comment by francovenica** [comment]
Question:
The date in the tooltip and the lable that group the tx in a specific day are off by 1 day, but that should be because of my timezone, but we discussed this was mostly a backend issue. Is it the same for you in your timezone?

https://tx-dates.web-core.pages.dev/rin:0x9913B9180C20C6b0F21B6480c84422F6ebc4B808/transactions/history

dates

**Comment by iamacook** [comment]
> Question: The date in the tooltip and the lable that group the tx in a specific day are off by 1 day, but that should be because of my timezone, but we discussed this was mostly a backend issue. Is it the same for you in your timezone?

No, it is a timezone issue.
